# This file created by conda-build 26.3.0
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_178394832832089/tzdata-feedstock/recipe, last modified Mon Jul 13 13:13:16 2026
# ------------------------------------------------

package:
  name: tzdata
  version: 2026c
source:
  - url: https://data.iana.org/time-zones/releases/tzdata2026c.tar.gz
    sha256: e4a178a4477f3d0ea77cc31828ff72aa38feff8d61aa13e7e99e142e9d902be4
  - url: https://data.iana.org/time-zones/releases/tzcode2026c.tar.gz
    sha256: b1cffc3ace4c4c7cd0efba2f7add86ec3d0b79da48bcf03582671fd3c8feace8
build:
  number: '0'
  noarch: generic
  ignore_run_exports_from:
    - clang_osx-arm64 20.*
    - macosx_deployment_target_osx-arm64 12.1.*
  string: he532380_0
requirements:
  build:
    - cctools 1021.4 h01d68c5_0
    - clang 20.1.8 h5e9ac1b_1
    - clang-20 20.1.8 default_h6c0b5b9_1
    - clang_impl_osx-arm64 20.1.8 h1ae22af_1
    - clang_osx-arm64 20.1.8 hf3c1794_1
    - compiler-rt 20.1.8 hf790f37_0
    - compiler-rt_osx-arm64 20.1.8 hf790f37_0
    - icu 78.3 hb5f10ac_1
    - ld64 954.16 hbcf198d_0
    - libclang-cpp20.1 20.1.8 default_h6c0b5b9_1
    - libcxx 22.1.2 hf894667_0
    - libiconv 1.18 h92f5915_0
    - libllvm20 20.1.8 h6e4320f_1
    - libxml2 2.14.6 h1ea6aa3_1
    - libzlib 1.3.2 hb4cf58c_0
    - llvm-tools 20.1.8 h3e84038_1
    - llvm-tools-20 20.1.8 h9115afe_1
    - lz4-c 1.9.4 hd7fd590_5
    - macosx_deployment_target_osx-arm64 12.1 h3601aa6_2
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.8.2 h8bbcb1d_0
    - zstd 1.5.7 h817c040_0
  host: []
  run: []
about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: CC-PDDC OR BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: The Time Zone Database (called tz, tzdb or zoneinfo)
  description: 'The Time Zone Database (called tz, tzdb or zoneinfo) contains code
    and

    data that represent the history of local time for many representative

    locations around the globe.  It is updated periodically to reflect

    changes made by political bodies to time zone boundaries, UTC offsets,

    and daylight-saving rules.

    '
extra:
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - pganssle
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/tzdata-feedstock
  sha: c170aa08e1ba54e30a8bda3281b463f077918508
  task_id: SE00M8zZTOq253H0KIYTYA
  task_run_id: '0'
  pbp_graph_uuid: 8bc6790e-cf33-4837-a484-2b82fb04c9d5
