c_compiler: vs2022
c_stdlib: vs
c_stdlib_version: '2022.14'
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: win-64
python: '3.11'
r_base: '3.4'
target_platform: win-64
vc: '14'
xz: '5'
