from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional, Union
from pydantic import Field, field_validator, AliasChoices, model_validator, ConfigDict
from pydantic.alias_generators import to_camel

from shared.schemas.base import APIModel
from api_gateway.schemas.common import PaginatedData
from shared.schemas.testcase import ReportAudioItem, ReportTestCaseItem

if TYPE_CHECKING:
    pass


class TestCaseAudioConfigItem(APIModel):
    id: Optional[int] = Field(None, alias='id', validation_alias='id')
    audio_id: Optional[Union[int, str]] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    audio_name: Optional[str] = Field(None, alias='audio_name', validation_alias=AliasChoices('audio_name', 'audioName'))
    spl: Optional[float] = Field(None, alias='spl', validation_alias='spl')
    playback_device_id: Optional[Union[int, str]] = Field(None, alias='playback_device_id', validation_alias=AliasChoices('playback_device_id', 'playbackDeviceId'))
    playback_device_name: Optional[str] = Field(None, alias='playback_device_name', validation_alias=AliasChoices('playback_device_name', 'playbackDeviceName'))
    play_order: Optional[int] = Field(None, alias='play_order', validation_alias=AliasChoices('play_order', 'playOrder'))

    @field_validator('spl', mode='before')
    @classmethod
    def _empty_spl_to_none(cls, v):
        if v == '' or v is None:
            return None
        try:
            return float(v)
        except (TypeError, ValueError):
            return None


class TestCaseBackgroundNoiseItem(APIModel):
    audio_id: Optional[Union[int, str]] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    spl: Optional[float] = Field(None, alias='spl', validation_alias='spl')
    device_ids: Optional[List[Union[int, str]]] = Field(None, alias='device_ids', validation_alias=AliasChoices('device_ids', 'deviceIds'))
    loop: Optional[bool] = Field(True, alias='loop', validation_alias='loop')


class TestCaseDimensionItem(APIModel):
    id: int = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    weight: Optional[float] = Field(None, alias='weight', validation_alias='weight')
    threshold: Optional[float] = Field(None, alias='threshold', validation_alias='threshold')
    test_type: Optional[str] = Field(None, alias='test_type', validation_alias=AliasChoices('test_type', 'testType'))


class RoundConfigItem(APIModel):
    """单轮配置项 — 只含结构性字段

    算法参数和参考参数不在 config.rounds[] 中：
      - algorithm_params → test_cases.algorithm_params 独立列（按轮分组 [{round_number, params}]）
      - reference_params → test_cases.reference_params 独立列（按轮分组 [{round_number, reference_params_path}]）
    """
    model_config = ConfigDict(extra='allow')

    # === 结构性字段 ===
    round_number: Optional[int] = Field(1, alias='round_number', validation_alias=AliasChoices('round_number', 'roundNumber'))
    audios: Optional[List[TestCaseAudioConfigItem]] = Field(default_factory=list, alias='audios', validation_alias='audios')
    background_noise: Optional[TestCaseBackgroundNoiseItem] = Field(None, alias='background_noise', validation_alias=AliasChoices('background_noise', 'backgroundNoise'))
    evaluation: Optional[Dict[str, Any]] = Field(None, alias='evaluation', validation_alias='evaluation')


class TestCaseConfig(APIModel):
    """测试用例配置 — 只含结构性配置
    config = { rounds, dimensions, background_noise, source_audio, auto_generated }
    算法参数和参考参数在独立列，不在 config 中
    """
    model_config = ConfigDict(extra='allow')
    rounds: Optional[List[RoundConfigItem]] = Field(default_factory=list, alias='rounds', validation_alias='rounds')
    dimensions: Optional[List[TestCaseDimensionItem]] = Field(default_factory=list, alias='dimensions', validation_alias='dimensions')
    background_noise: Optional[Dict[str, Any]] = Field(None, alias='background_noise', validation_alias=AliasChoices('background_noise', 'backgroundNoise'))
    source_audio: Optional[str] = Field(None, alias='source_audio', validation_alias=AliasChoices('source_audio', 'sourceAudio'))
    auto_generated: Optional[bool] = Field(False, alias='auto_generated', validation_alias=AliasChoices('auto_generated', 'autoGenerated'))


class TestCaseListItem(APIModel):
    id: str = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    group_id: Optional[str] = Field(None, alias='group_id', validation_alias=AliasChoices('group_id', 'groupId'))
    group_name: Optional[str] = Field(None, alias='group_name', validation_alias=AliasChoices('group_name', 'groupName'))
    type: Optional[str] = Field(None, alias='type', validation_alias='type')
    tags: List[str] = Field(default_factory=list, alias='tags', validation_alias='tags')
    config: TestCaseConfig = Field(default_factory=TestCaseConfig, alias='config', validation_alias='config')
    algorithm_params: Optional[Any] = Field(None, alias='algorithm_params', validation_alias=AliasChoices('algorithm_params', 'algorithmParams'))
    reference_params: Optional[Any] = Field(None, alias='reference_params', validation_alias=AliasChoices('reference_params', 'referenceParams'))
    algorithm_type: Optional[str] = Field(None, alias='algorithm_type', validation_alias=AliasChoices('algorithm_type', 'algorithmType'))
    created_at: Optional[str] = Field(None, alias='created_at', validation_alias=AliasChoices('created_at', 'createdAt'))
    updated_at: Optional[str] = Field(None, alias='updated_at', validation_alias=AliasChoices('updated_at', 'updatedAt'))
    total_duration: Optional[float] = Field(None, alias='total_duration', validation_alias=AliasChoices('total_duration', 'totalDuration'))


class TestCaseListData(PaginatedData[TestCaseListItem]):
    pass


class TestCaseDimensionBrief(APIModel):
    id: int = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    type: Optional[str] = Field(None, alias='type', validation_alias='type')


class TestCaseDetailData(APIModel):
    id: str = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    group_id: Optional[str] = Field(None, alias='group_id', validation_alias=AliasChoices('group_id', 'groupId'))
    group_name: Optional[str] = Field(None, alias='group_name', validation_alias=AliasChoices('group_name', 'groupName'))
    group: Optional[Dict[str, Any]] = Field(None, alias='group', validation_alias='group')
    type: Optional[str] = Field(None, alias='type', validation_alias='type')
    config: TestCaseConfig = Field(default_factory=TestCaseConfig, alias='config', validation_alias='config')
    algorithm_params: Optional[Any] = Field(None, alias='algorithm_params', validation_alias=AliasChoices('algorithm_params', 'algorithmParams'))
    reference_params: Optional[Any] = Field(None, alias='reference_params', validation_alias=AliasChoices('reference_params', 'referenceParams'))
    tags: List[str] = Field(default_factory=list, alias='tags', validation_alias='tags')
    audios: List[TestCaseAudioConfigItem] = Field(default_factory=list, alias='audios', validation_alias='audios')
    dimensions: List[TestCaseDimensionBrief] = Field(default_factory=list, alias='dimensions', validation_alias='dimensions')
    algorithm_type: Optional[str] = Field(None, alias='algorithm_type', validation_alias=AliasChoices('algorithm_type', 'algorithmType'))
    created_at: Optional[str] = Field(None, alias='created_at', validation_alias=AliasChoices('created_at', 'createdAt'))
    updated_at: Optional[str] = Field(None, alias='updated_at', validation_alias=AliasChoices('updated_at', 'updatedAt'))
    total_duration: Optional[float] = Field(None, alias='total_duration', validation_alias=AliasChoices('total_duration', 'totalDuration'))


class TestCasePreviewData(APIModel):
    test_case_id: str = Field(..., alias='test_case_id', validation_alias=AliasChoices('test_case_id', 'testCaseId'))
    preview_task_id: Optional[str] = Field(None, alias='preview_task_id', validation_alias=AliasChoices('preview_task_id', 'previewTaskId'))
    status: str = Field(..., alias='status', validation_alias='status')
    message: Optional[str] = Field(None, alias='message', validation_alias='message')
    duration: Optional[float] = Field(None, alias='duration', validation_alias='duration')
    playback_mode: Optional[str] = Field('backend', alias='playback_mode', validation_alias=AliasChoices('playback_mode', 'playbackMode'))
    audio_id: Optional[Union[int, str]] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    audio_stream_url: Optional[str] = Field(None, alias='audio_stream_url', validation_alias=AliasChoices('audio_stream_url', 'audioStreamUrl'))
    # 多轮音频连续播放
    audio_stream_urls: Optional[List[str]] = Field(None, alias='audio_stream_urls', validation_alias=AliasChoices('audio_stream_urls', 'audioStreamUrls'))


class TestCaseStopPreviewData(APIModel):
    test_case_id: str = Field(..., alias='test_case_id', validation_alias=AliasChoices('test_case_id', 'testCaseId'))
    status: str = Field(..., alias='status', validation_alias='status')
    message: Optional[str] = Field(None, alias='message', validation_alias='message')


class TestCaseStatsData(APIModel):
    total_count: int = Field(..., alias='total_count', validation_alias=AliasChoices('total_count', 'totalCount'))
    by_group: Dict[str, int] = Field(default_factory=dict, alias='by_group', validation_alias=AliasChoices('by_group', 'byGroup'))
    recent_updates: List[Dict[str, Any]] = Field(default_factory=list, alias='recent_updates', validation_alias=AliasChoices('recent_updates', 'recentUpdates'))


class TagListData(APIModel):
    items: List[str] = Field(..., alias='items', validation_alias='items')


class TagCategoryItem(APIModel):
    id: int = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    sort_order: int = Field(0, alias='sort_order', validation_alias=AliasChoices('sort_order', 'sortOrder'))
    tag_count: int = Field(0, alias='tag_count', validation_alias=AliasChoices('tag_count', 'tagCount'))
    created_at: Optional[str] = Field(None, alias='created_at', validation_alias=AliasChoices('created_at', 'createdAt'))
    updated_at: Optional[str] = Field(None, alias='updated_at', validation_alias=AliasChoices('updated_at', 'updatedAt'))


class TagCategoryListData(APIModel):
    items: List[TagCategoryItem] = Field(..., alias='items', validation_alias='items')
    total: int = Field(..., alias='total', validation_alias='total')


class TagCategoryCreateSchema(APIModel):
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    sort_order: Optional[int] = Field(0, alias='sort_order', validation_alias=AliasChoices('sort_order', 'sortOrder'))


class TagCategoryUpdateSchema(APIModel):
    id: Optional[int] = Field(None, alias='id', validation_alias='id')
    name: Optional[str] = Field(None, alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    sort_order: Optional[int] = Field(None, alias='sort_order', validation_alias=AliasChoices('sort_order', 'sortOrder'))


class TagItem(APIModel):
    id: int = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    category_id: Optional[int] = Field(None, alias='category_id', validation_alias=AliasChoices('category_id', 'categoryId'))
    category_name: Optional[str] = Field(None, alias='category_name', validation_alias=AliasChoices('category_name', 'categoryName'))
    created_at: Optional[str] = Field(None, alias='created_at', validation_alias=AliasChoices('created_at', 'createdAt'))
    updated_at: Optional[str] = Field(None, alias='updated_at', validation_alias=AliasChoices('updated_at', 'updatedAt'))


class TagDetailListData(APIModel):
    items: List[TagItem] = Field(..., alias='items', validation_alias='items')
    total: int = Field(..., alias='total', validation_alias='total')


class TagCreateSchema(APIModel):
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    category_id: Optional[int] = Field(None, alias='category_id', validation_alias=AliasChoices('category_id', 'categoryId'))


class TagUpdateSchema(APIModel):
    id: Optional[int] = Field(None, alias='id', validation_alias='id')
    name: Optional[str] = Field(None, alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    color: Optional[str] = Field(None, alias='color', validation_alias='color')
    category_id: Optional[int] = Field(None, alias='category_id', validation_alias=AliasChoices('category_id', 'categoryId'))


class TestCaseExportJsonData(APIModel):
    test_cases: List["TestCaseExportItem"] = Field(..., alias='test_cases', validation_alias=AliasChoices('test_cases', 'testCases'))
    exported_at: str = Field(..., alias='exported_at', validation_alias=AliasChoices('exported_at', 'exportedAt'))
    total_count: int = Field(..., alias='total_count', validation_alias=AliasChoices('total_count', 'totalCount'))


class TestCaseImportResult(APIModel):
    imported_count: int = Field(..., alias='imported_count', validation_alias=AliasChoices('imported_count', 'importedCount'))
    errors: List[Any] = Field(default_factory=list, alias='errors', validation_alias='errors')


class TestCaseExportTagItem(APIModel):
    tag_id: int = Field(..., alias='tag_id', validation_alias=AliasChoices('tag_id', 'tagId'))
    tag_name: str = Field(..., alias='tag_name', validation_alias=AliasChoices('tag_name', 'tagName'))


class TestCaseExportAudioItem(APIModel):
    audio_id: Optional[int] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    audio_name: Optional[str] = Field(None, alias='audio_name', validation_alias=AliasChoices('audio_name', 'audioName'))
    spl: Optional[float] = Field(None, alias='spl', validation_alias='spl')
    playback_device_id: Optional[int] = Field(None, alias='playback_device_id', validation_alias=AliasChoices('playback_device_id', 'playbackDeviceId'))
    playback_device_name: Optional[str] = Field(None, alias='playback_device_name', validation_alias=AliasChoices('playback_device_name', 'playbackDeviceName'))
    play_order: Optional[int] = Field(None, alias='play_order', validation_alias=AliasChoices('play_order', 'playOrder'))


class TestCaseExportItem(APIModel):
    id: str = Field(..., alias='id', validation_alias='id')
    name: str = Field(..., alias='name', validation_alias='name')
    description: Optional[str] = Field(None, alias='description', validation_alias='description')
    group: Optional[str] = Field(None, alias='group', validation_alias='group')
    group_id: Optional[str] = Field(None, alias='group_id', validation_alias=AliasChoices('group_id', 'groupId'))
    tags: List[str] = Field(default_factory=list, alias='tags', validation_alias='tags')
    tag_items: List[TestCaseExportTagItem] = Field(default_factory=list, alias='tag_items', validation_alias=AliasChoices('tag_items', 'tagItems'))
    dimensions: List[str] = Field(default_factory=list, alias='dimensions', validation_alias='dimensions')
    dimension_ids: List[int] = Field(default_factory=list, alias='dimension_ids', validation_alias=AliasChoices('dimension_ids', 'dimensionIds'))
    playback_devices: List[str] = Field(default_factory=list, alias='playback_devices', validation_alias=AliasChoices('playback_devices', 'playbackDevices'))
    audios: List[TestCaseExportAudioItem] = Field(default_factory=list, alias='audios', validation_alias='audios')
    audio_details: Optional[str] = Field(None, alias='audio_details', validation_alias=AliasChoices('audio_details', 'audioDetails'))
    noise_name: Optional[str] = Field(None, alias='noise_name', validation_alias=AliasChoices('noise_name', 'noiseName'))
    noise_spl: Optional[Any] = Field(None, alias='noise_spl', validation_alias=AliasChoices('noise_spl', 'noiseSpl'))
    noise_audio_id: Optional[int] = Field(None, alias='noise_audio_id', validation_alias=AliasChoices('noise_audio_id', 'noiseAudioId'))
    config: Dict[str, Any] = Field(default_factory=dict, alias='config', validation_alias='config')
    raw_config: Optional[str] = Field(None, alias='raw_config', validation_alias=AliasChoices('raw_config', 'rawConfig'))


class TestCaseAudioConfigRequest(APIModel):
    audio_id: Optional[int] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    spl: Optional[float] = Field(None, alias='spl', validation_alias='spl')
    playback_device_id: Optional[int] = Field(None, alias='playback_device_id', validation_alias=AliasChoices('playback_device_id', 'playbackDeviceId'))
    play_order: Optional[int] = Field(None, alias='play_order', validation_alias=AliasChoices('play_order', 'playOrder'))


class TestCaseBackgroundNoiseRequest(APIModel):
    audio_id: Optional[int] = Field(None, alias='audio_id', validation_alias=AliasChoices('audio_id', 'audioId'))
    spl: Optional[float] = Field(None, alias='spl', validation_alias='spl')
    device_ids: Optional[List[Union[int, str]]] = Field(None, alias='device_ids', validation_alias=AliasChoices('device_ids', 'deviceIds'))


class TestCaseDimensionItemRequest(APIModel):
    id: Optional[int] = Field(None, alias='id', validation_alias='id')
    name: Optional[str] = Field(None, alias='name', validation_alias='name')
    display_name: Optional[str] = Field(None, alias='display_name', validation_alias=AliasChoices('display_name', 'displayName'))
    weight: Optional[float] = Field(None, alias='weight', validation_alias='weight')
    threshold: Optional[float] = Field(None, alias='threshold', validation_alias='threshold')


class AlgorithmParamItem(APIModel):
    """算法参数项 — {field_code, field_value}

    field_value 类型由 case_algorithm_params 表的 param_type 定义决定，
    Schema 层不限制具体类型，支持 str/int/float/bool/list/dict 等。
    """
    model_config = ConfigDict(extra='allow')

    field_code: Optional[str] = Field(None, alias='field_code', validation_alias=AliasChoices('field_code', 'fieldCode'))
    field_value: Optional[Any] = Field(None, alias='field_value', validation_alias=AliasChoices('field_value', 'fieldValue'))

    @staticmethod
    def convert_params(params) -> Optional[List['AlgorithmParamItem']]:
        if not params:
            return None
        if isinstance(params, list):
            result = []
            for item in params:
                if isinstance(item, dict):
                    field_value = item.get('field_value')
                    result.append(AlgorithmParamItem(
                        field_code=item.get('field_code'),
                        field_value=field_value
                    ))
                elif isinstance(item, AlgorithmParamItem):
                    result.append(item)
            return result if result else None
        elif isinstance(params, dict):
            result = []
            for key, value in params.items():
                result.append(AlgorithmParamItem(
                    field_code=key,
                    field_value=value
                ))
            return result if result else None
        return params


class ReferenceParamItem(APIModel):
    model_config = ConfigDict(extra='allow')

    code: Optional[str] = Field(None, alias='code', validation_alias=AliasChoices('code', 'code'))
    type: Optional[str] = Field(None, alias='type', validation_alias=AliasChoices('type', 'type'))
    value: Optional[Union[str, Dict[str, Any], List[Any]]] = Field(None, alias='value', validation_alias=AliasChoices('value', 'value'))
    annotation_code: Optional[str] = Field(None, alias='annotation_code', validation_alias=AliasChoices('annotation_code', 'annotationCode'))
    annotation_format: Optional[str] = Field(None, alias='annotation_format', validation_alias=AliasChoices('annotation_format', 'annotationFormat'))

    @staticmethod
    def convert_params(params) -> Optional[List['ReferenceParamItem']]:
        if not params:
            return None
        if isinstance(params, list):
            result = []
            for item in params:
                if isinstance(item, dict):
                    result.append(ReferenceParamItem(
                        code=item.get('code'),
                        type=item.get('type'),
                        value=item.get('value'),
                        annotation_code=item.get('annotation_code'),
                        annotation_format=item.get('annotation_format')
                    ))
                elif isinstance(item, ReferenceParamItem):
                    result.append(item)
            return result if result else None
        return params


class TestCaseCreateSchema(APIModel):
    name: str = Field(..., validation_alias=AliasChoices('name', 'caseName', 'case_name'))
    description: Optional[str] = Field(None, validation_alias=AliasChoices('description', 'Description'))
    group_id: Optional[str] = Field(None, validation_alias=AliasChoices('group_id', 'groupId'))
    group: Optional[str] = Field(None, alias='group', validation_alias='group')
    test_type: Optional[str] = Field('api', alias='test_type', validation_alias=AliasChoices('test_type', 'testType'))
    config: Optional[Dict[str, Any]] = Field(None, alias='config', validation_alias='config')
    tags: Optional[List[str]] = Field(None, alias='tags', validation_alias='tags')
    background_noise_id: Optional[int] = Field(None, alias='background_noise_id', validation_alias=AliasChoices('background_noise_id', 'backgroundNoiseId'))
    background_noise_spl: Optional[float] = Field(None, alias='background_noise_spl', validation_alias=AliasChoices('background_noise_spl', 'backgroundNoiseSpl'))
    audios: Optional[List[TestCaseAudioConfigRequest]] = Field(None, alias='audios', validation_alias='audios')
    dimensions: Optional[Any] = Field(None, alias='dimensions', validation_alias='dimensions')
    algorithm_type: Optional[str] = Field(None, alias='algorithm_type', validation_alias=AliasChoices('algorithm_type', 'algorithmType'))
    # 按轮分组：[{round_number, params:[{field_code, field_value}]}]，兼容旧平面格式 [{field_code, field_value}]
    algorithm_params: Optional[Any] = Field(None, alias='algorithm_params', validation_alias=AliasChoices('algorithm_params', 'algorithmParams'))
    # 按轮分组：[{round_number, reference_params_path}]，兼容旧格式
    reference_params: Optional[Any] = Field(None, alias='reference_params', validation_alias=AliasChoices('reference_params', 'referenceParams'))

    @field_validator('algorithm_params', mode='before')
    @classmethod
    def coerce_dict_to_list(cls, v):
        if isinstance(v, dict):
            # 旧 dict 格式 → 平面 list（向后兼容）
            return [
                {'field_code': k, 'field_value': val}
                for k, val in v.items()
            ]
        return v

    def get_algorithm_params_dict(self) -> Optional[List[Dict[str, Any]]]:
        """返回按轮分组的 algorithm_params

        新格式：[{round_number, params:[{field_code, field_value}]}]
        旧格式（平面 [{field_code, field_value}]）会被包装为 round_number=1 的单轮
        """
        if not self.algorithm_params:
            return None
        # 检测格式：新格式第一个元素有 round_number 键
        if isinstance(self.algorithm_params, list) and self.algorithm_params:
            first = self.algorithm_params[0]
            if isinstance(first, dict) and 'round_number' in first:
                # 新格式，直接返回
                return self.algorithm_params
            if isinstance(first, dict) and 'params' in first and 'field_code' not in first:
                # 新格式（params 键）
                return self.algorithm_params
        # 旧格式（平面 [{field_code, field_value}]） → 包装为 round_number=1
        result = []
        for p in self.algorithm_params:
            if isinstance(p, dict):
                item = dict(p)
                # field_value 保持原始类型（list/dict/str/number）
                result.append(item)
        if result:
            return [{'round_number': 1, 'params': result}]
        return None

    def get_reference_params_dict(self) -> Optional[List[Dict[str, Any]]]:
        """返回按轮分组的 reference_params"""
        if not self.reference_params:
            return None
        if isinstance(self.reference_params, list):
            return self.reference_params
        return None


class TestCasePreviewRequest(APIModel):
    offset: Optional[float] = Field(0, alias='offset', validation_alias='offset')
    preview_type: Optional[str] = Field(None, alias='preview_type', validation_alias=AliasChoices('preview_type', 'previewType'))
    playback_mode: Optional[str] = Field('backend', alias='playback_mode', validation_alias=AliasChoices('playback_mode', 'playbackMode'))

    @field_validator('offset', mode='before')
    @classmethod
    def convert_offset_to_int(cls, v):
        if v is None:
            return 0
        return int(v)

    @field_validator('playback_mode', mode='before')
    @classmethod
    def validate_playback_mode(cls, v):
        if v is None:
            return 'backend'
        if v not in ['frontend', 'backend']:
            return 'backend'
        return v


class TestCaseBatchActionRequest(APIModel):
    ids: List[str] = Field(..., alias='ids', validation_alias='ids')
    action: str = Field(..., alias='action', validation_alias='action')
    target_group_id: Optional[str] = Field(None, alias='target_group_id', validation_alias=AliasChoices('target_group_id', 'targetGroupId'))
    algorithm_params: Optional[Dict[str, Any]] = Field(None, alias='algorithm_params', validation_alias=AliasChoices('algorithm_params', 'algorithmParams'))
    playback_devices: Optional[Dict[str, Any]] = Field(None, alias='playback_devices', validation_alias=AliasChoices('playback_devices', 'playbackDevices'))
    spl: Optional[Union[float, Dict[str, Any]]] = Field(None, alias='spl', validation_alias=AliasChoices('spl', 'spl'))
    noise_spl: Optional[float] = Field(None, alias='noise_spl', validation_alias=AliasChoices('noise_spl', 'noiseSpl'))
    noise_audio_id: Optional[Union[int, str]] = Field(None, alias='noise_audio_id', validation_alias=AliasChoices('noise_audio_id', 'noiseAudioId'))
    noise_device_ids: Optional[List[Union[int, str]]] = Field(None, alias='noise_device_ids', validation_alias=AliasChoices('noise_device_ids', 'noiseDeviceIds'))
    group_name: Optional[str] = Field(None, alias='group_name', validation_alias=AliasChoices('group_name', 'groupName'))
    tags: Optional[List[str]] = Field(None, alias='tags', validation_alias='tags')
    dimensions: Optional[List[Dict[str, Any]]] = Field(None, alias='dimensions', validation_alias='dimensions')
    old_tag_name: Optional[str] = Field(None, alias='old_tag_name', validation_alias=AliasChoices('old_tag_name', 'oldTagName'))
    new_tag_name: Optional[str] = Field(None, alias='new_tag_name', validation_alias=AliasChoices('new_tag_name', 'newTagName'))


class TestCaseExportRequest(APIModel):
    ids: List[str] = Field(default_factory=list, alias='ids', validation_alias='ids')
    format: Optional[str] = Field('json', alias='format', validation_alias='format')
    include_deleted: Optional[bool] = Field(False, alias='include_deleted', validation_alias=AliasChoices('include_deleted', 'includeDeleted'))


class TestCaseImportRequest(APIModel):
    file_name: Optional[str] = Field(None, alias='file_name', validation_alias=AliasChoices('file_name', 'fileName'))
    file_content: Optional[str] = Field(None, alias='file_content', validation_alias=AliasChoices('file_content', 'fileContent'))
    group_id: Optional[str] = Field(None, alias='group_id', validation_alias=AliasChoices('group_id', 'groupId'))
    overwrite: Optional[bool] = Field(False, alias='overwrite', validation_alias='overwrite')


class TestCaseUpdateSchema(APIModel):
    id: Optional[str] = Field(None, alias='id', validation_alias='id')
    name: Optional[str] = Field(None, alias='name', validation_alias=AliasChoices('name', 'Name'))
    description: Optional[str] = Field(None, alias='description', validation_alias=AliasChoices('description', 'Description'))
    group_id: Optional[str] = Field(None, alias='group_id', validation_alias=AliasChoices('group_id', 'groupId'))
    group: Optional[str] = Field(None, alias='group', validation_alias='group')
    test_type: Optional[str] = Field(None, alias='test_type', validation_alias=AliasChoices('test_type', 'testType'))
    config: Optional[Dict[str, Any]] = Field(None, alias='config', validation_alias='config')
    tags: Optional[List[str]] = Field(None, alias='tags', validation_alias='tags')
    background_noise_id: Optional[int] = Field(None, alias='background_noise_id', validation_alias=AliasChoices('background_noise_id', 'backgroundNoiseId'))
    background_noise_spl: Optional[float] = Field(None, alias='background_noise_spl', validation_alias=AliasChoices('background_noise_spl', 'backgroundNoiseSpl'))
    audios: Optional[List[TestCaseAudioConfigRequest]] = Field(None, alias='audios', validation_alias='audios')
    dimensions: Optional[Any] = Field(None, alias='dimensions', validation_alias='dimensions')
    algorithm_type: Optional[str] = Field(None, alias='algorithm_type', validation_alias=AliasChoices('algorithm_type', 'algorithmType'))
    # 按轮分组：[{round_number, params:[{field_code, field_value}]}]，兼容旧平面格式
    algorithm_params: Optional[Any] = Field(None, alias='algorithm_params', validation_alias=AliasChoices('algorithm_params', 'algorithmParams'))
    # 按轮分组：[{round_number, reference_params_path}]
    reference_params: Optional[Any] = Field(None, alias='reference_params', validation_alias=AliasChoices('reference_params', 'referenceParams'))

    @field_validator('algorithm_params', mode='before')
    @classmethod
    def coerce_dict_to_list(cls, v):
        if isinstance(v, dict):
            return [
                {'field_code': k, 'field_value': val}
                for k, val in v.items()
            ]
        return v

    def get_algorithm_params_dict(self) -> Optional[List[Dict[str, Any]]]:
        """返回按轮分组的 algorithm_params"""
        if not self.algorithm_params:
            return None
        if isinstance(self.algorithm_params, list) and self.algorithm_params:
            first = self.algorithm_params[0]
            if isinstance(first, dict) and 'round_number' in first:
                return self.algorithm_params
            if isinstance(first, dict) and 'params' in first and 'field_code' not in first:
                return self.algorithm_params
        result = []
        for p in self.algorithm_params:
            if isinstance(p, dict):
                item = dict(p)
                # field_value 保持原始类型（list/dict/str/number）
                # 历史遗留：旧代码用 str() 转换，会导致 list/dict 变成 Python repr 字符串，无法 JSON 解析
                # 现在原样保留，JSON 列原生支持 list/dict
                result.append(item)
        if result:
            return [{'round_number': 1, 'params': result}]
        return None

    def get_reference_params_dict(self) -> Optional[List[Dict[str, Any]]]:
        if not self.reference_params:
            return None
        if isinstance(self.reference_params, list):
            return self.reference_params
        return None


