/**
 * TestCase 领域模型 —— camelCase
 * 对应后端 api_gateway/schemas/testcase.py::TestCaseListItem
 *
 * config/algorithmParams/referenceParams 为透传结构，
 * 但 Domain 层统一 camelCase，Infrastructure adapter 层负责
 * 对 config 内所有 snake_case key 做深度递归转换。
 */

// ============================================================
// rounds-as-top-level 架构核心类型（权威定义；Presentation 层 re-export）
// ============================================================

/**
 * 算法参数项 — 通用算法参数容器
 * 对应后端 AlgorithmParamItem: {field_code, field_value}
 * Domain 层统一 camelCase，adapter 层负责 snake_case ⇄ camelCase 转换
 */
export interface AlgorithmParamItem {
  fieldCode: string
  fieldValue: unknown
}

/**
 * 按轮分组的算法参数 — 对应 test_cases.algorithm_params 列
 * 每个元素描述某一轮的算法参数集合
 */
export interface RoundAlgorithmParams {
  roundNumber: number
  params: AlgorithmParamItem[]
}

/**
 * 按轮分组的参考参数路径 — 对应 test_cases.reference_params 列
 * 每个元素描述某一轮的参考参数文件路径
 */
export interface RoundReferenceParams {
  roundNumber: number
  referenceParamsPath: string
}

/**
 * 音频配置项 — 轮次内音频
 * testType 已移除，由父级用例的 testType 决定
 */
export interface AudioConfig {
  audioId: string
  playbackDeviceId?: string
  spl?: number
  playOrder: number
}

/**
 * 评估维度配置
 */
export interface DimensionConfig {
  id?: string | number
  name: string
  weight: number
  threshold: number
}

/**
 * 背景噪声配置 — 新增 loop 字段
 */
export interface BackgroundNoiseConfig {
  audioId: string
  deviceIds: string[]
  spl: number
  loop?: boolean
}

/**
 * 轮次评估配置
 */
export interface RoundEvaluationConfig {
  enabled: boolean
  dimensions: DimensionConfig[]
}

/**
 * 单轮配置项 — rounds-as-top-level 架构的核心数据结构
 * 对应后端 RoundConfigItem
 *
 * 仅保留结构性字段：roundNumber, audios, backgroundNoise, evaluation
 * 算法参数和参考参数已移至 test_cases 表的独立列：
 *   - algorithm_params: RoundAlgorithmParams[]
 *   - reference_params: RoundReferenceParams[]
 */
export interface RoundConfigItem {
  roundNumber: number
  audios: AudioConfig[]
  backgroundNoise?: BackgroundNoiseConfig
  evaluation?: RoundEvaluationConfig
  // 待后端契约明确后移除：兼容历史数据中的透传字段
  [key: string]: unknown
}

/**
 * 测试用例配置 — rounds-as-top-level 架构
 * config = { rounds: [...], dimensions: [...] }
 * Domain 层统一 camelCase，adapter 层负责 snake_case ⇄ camelCase 深度转换
 */
export interface TestCaseConfig {
  rounds?: RoundConfigItem[]
  dimensions?: DimensionConfig[]
  /** 旧版 flat 格式遗留字段（历史数据兼容）：轮次内音频列表 */
  audios?: AudioConfig[]
  /** 旧版 flat 格式遗留字段（历史数据兼容）：背景噪声配置 */
  backgroundNoise?: BackgroundNoiseConfig
  voiceprintConfig?: {
    enabled?: boolean
    audio?: { id?: string }
    device?: { id?: string }
    spl?: number
    waitTime?: number
  }
  /** case 级全局背景噪声（跨所有轮次持续播放，优先于 round 级） */
  backgroundNoiseCase?: BackgroundNoiseConfig
  /** 源音频路径 */
  sourceAudio?: string
  /** 是否自动生成 */
  autoGenerated?: boolean
  // 待后端契约明确后移除：兼容历史数据中的透传字段
  [key: string]: unknown
}

/** 测试用例标签（可能是 id/name 对象或字符串） */
export type TestCaseTag = string | { id: number; name: string }

/** 用例列表行（TestCaseListItem → camelCase；config/算法参数经 adapter 深度 camelize） */
export interface TestCase {
  id: string | number
  name: string
  description?: string
  type?: string
  testType?: 'api' | 'e2e'
  config?: TestCaseConfig
  /** 按轮分组的算法参数（对应 test_cases.algorithm_params，adapter 已 camelize） */
  algorithmParams?: RoundAlgorithmParams[]
  /** 按轮分组的参考参数路径（对应 test_cases.reference_params，adapter 已 camelize） */
  referenceParams?: RoundReferenceParams[]
  groupId?: string | number
  groupName?: string
  tags?: TestCaseTag[]
  algorithmType?: string
  createdAt?: string
  updatedAt?: string
  deleted?: boolean
  totalDuration?: number
}

export interface TestCaseGroup {
  id: string | number
  name: string
  description?: string
  algorithmType?: string
  createdAt?: string
  updatedAt?: string
  /** 分组下用例数（后端 groups 接口附加字段） */
  testCaseCount?: number
}

/** 用例创建/编辑表单（前端 Domain → adapter 转 DTO） */
export interface TestCaseDraft {
  id?: string | number
  name: string
  description?: string
  type?: string
  testType?: 'api' | 'e2e'
  config?: TestCaseConfig
  groupId?: string | number
  group?: string
  tags?: string[]
  algorithmType?: string
  algorithmParams?: RoundAlgorithmParams[]
  referenceParams?: RoundReferenceParams[]
}

// ===== 表单/操作类型（前端本地 Domain） =====

/**
 * 测试用例表单数据（兼容历史表单组件）
 * config 必填：创建/编辑/回填场景下表单必然携带完整配置；
 * 后端缺省字段由 adapter 兜底补齐（见 normalizeTestCaseConfig 调用方）
 */
export interface TestCaseFormData {
  id?: string | number
  name: string
  description?: string
  type?: string
  testType?: 'api' | 'e2e'
  config: TestCaseConfig
  groupId?: string | number
  group?: string
  /** 分组名称冗余字段（历史表单组件展示用） */
  groupName?: string
  tags?: string[]
  tagsInput?: string
  algorithmType?: string
  /** 按轮分组的算法参数（camelCase；adapter 出口为 snake_case algorithm_params） */
  algorithmParams?: RoundAlgorithmParams[]
  /** 按轮分组的参考参数路径（camelCase；adapter 出口为 snake_case reference_params） */
  referenceParams?: RoundReferenceParams[]
  /** 编辑前原始分组名（前端本地状态，用于编辑时检测分组变更） */
  _originalGroup?: string
  /** 编辑前原始分组 id（前端本地状态） */
  _originalGroupId?: string
}

/** 分组表单数据 */
export interface GroupFormData {
  name: string
  description?: string
  parentId?: string | number
  algorithmType?: string
}

/** 用例操作类型 */
export type TestCaseAction = 'add' | 'edit' | 'delete' | 'run' | 'duplicate'

// ===== 用例导入/导出领域类型（原 TestCaseModal/types.ts 内联定义下沉） =====

/** 分组统计（导出表单展示：分组名 + 各类型用例数） */
export interface GroupStat {
  name: string
  total: number
  api: number
  e2e: number
}

/** 导出表单数据 */
export interface ExportFormData {
  groups: string[]
  testType: string
  format: string
  includeConfig: boolean
  includeDeleted: boolean
}

/** 导入预览行（update = 覆盖已有，insert = 新增） */
export interface ImportPreviewItem {
  name: string
  type: string
  group: string
  operation: 'update' | 'insert'
}

/** 导入预览数据（Excel 解析结果统计） */
export interface ImportPreviewData {
  total: number
  items: ImportPreviewItem[]
  audioConfigsCount: number
  dimensionsCount: number
  tagsCount: number
  groupsCount: number
  sheetNames: string[]
}

// ===== 声纹/干扰人算法参数载荷（algorithmParams 中的结构化 fieldValue） =====

/**
 * 单个干扰人配置
 * 在 algorithmParams 中以 field_code = 'interferers' 存储
 */
export interface InterfererConfigItem {
  audioId?: string
  audioName?: string
  playbackDeviceId?: string
  /** 设备名（统一标注文件导入时无 ID，仅设备名） */
  playbackDeviceName?: string
  spl: number
  startDelay: number
  loop: boolean
}
