"""时间戳对齐常量"""

# 对齐常量
MAX_ALIGNMENT_OFFSET = 30.0
MIN_OVERLAP_THRESHOLD = 0.5
MAX_CANDIDATE_PAIRS = 100
MIN_GAP_MATCH_TOLERANCE = 0.5
GAP_PATTERN_MIN_SEGMENTS = 3
MIN_REF_START_TIME = -0.5
MIN_TEXT_SIMILARITY = 0.3
MIN_CONTENT_MATCH_PAIRS = 2
CONTENT_ALIGNMENT_SKIP_PENALTY = -0.1
CONTENT_ALIGNMENT_CONFIDENCE_THRESHOLD = 0.5
CONTENT_OUTLIER_OFFSET_THRESHOLD = 2.0
