# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_test_service_pb2 as api__test__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_test_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class APITestServiceStub:
    """===== API 测试服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAPITest = channel.unary_unary(
                '/api_test_service.APITestService/CreateAPITest',
                request_serializer=api__test__service__pb2.CreateAPITestRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.CreateAPITestResponse.FromString,
                _registered_method=True)
        self.StartAPITest = channel.unary_unary(
                '/api_test_service.APITestService/StartAPITest',
                request_serializer=api__test__service__pb2.StartAPITestRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.StartAPITestResponse.FromString,
                _registered_method=True)
        self.StopAPITest = channel.unary_unary(
                '/api_test_service.APITestService/StopAPITest',
                request_serializer=api__test__service__pb2.StopAPITestRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.StopAPITestResponse.FromString,
                _registered_method=True)
        self.GetAPITestStatus = channel.unary_unary(
                '/api_test_service.APITestService/GetAPITestStatus',
                request_serializer=api__test__service__pb2.GetAPITestStatusRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.APITestStatusResponse.FromString,
                _registered_method=True)
        self.CreateAPIConfig = channel.unary_unary(
                '/api_test_service.APITestService/CreateAPIConfig',
                request_serializer=api__test__service__pb2.CreateAPIConfigRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.CreateAPIConfigResponse.FromString,
                _registered_method=True)
        self.UpdateAPIConfig = channel.unary_unary(
                '/api_test_service.APITestService/UpdateAPIConfig',
                request_serializer=api__test__service__pb2.UpdateAPIConfigRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.UpdateAPIConfigResponse.FromString,
                _registered_method=True)
        self.DeleteAPIConfig = channel.unary_unary(
                '/api_test_service.APITestService/DeleteAPIConfig',
                request_serializer=api__test__service__pb2.DeleteAPIConfigRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.DeleteAPIConfigResponse.FromString,
                _registered_method=True)
        self.ListAPIConfigs = channel.unary_unary(
                '/api_test_service.APITestService/ListAPIConfigs',
                request_serializer=api__test__service__pb2.ListAPIConfigsRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.ListAPIConfigsResponse.FromString,
                _registered_method=True)
        self.GetAPIConfig = channel.unary_unary(
                '/api_test_service.APITestService/GetAPIConfig',
                request_serializer=api__test__service__pb2.GetAPIConfigRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.GetAPIConfigResponse.FromString,
                _registered_method=True)
        self.TestAPIConnection = channel.unary_unary(
                '/api_test_service.APITestService/TestAPIConnection',
                request_serializer=api__test__service__pb2.TestAPIConnectionRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.TestAPIConnectionResponse.FromString,
                _registered_method=True)
        self.StopAPITestConfig = channel.unary_unary(
                '/api_test_service.APITestService/StopAPITestConfig',
                request_serializer=api__test__service__pb2.StopAPITestConfigRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.StopAPITestConfigResponse.FromString,
                _registered_method=True)


class APITestServiceServicer:
    """===== API 测试服务 =====
    """

    def CreateAPITest(self, request, context):
        """创建 API 测试任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAPITest(self, request, context):
        """启动 API 测试
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAPITest(self, request, context):
        """停止 API 测试
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAPITestStatus(self, request, context):
        """获取 API 测试状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIConfig(self, request, context):
        """===== API 配置 CRUD =====
        创建 API 配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAPIConfig(self, request, context):
        """更新 API 配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAPIConfig(self, request, context):
        """删除 API 配置（软删除）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAPIConfigs(self, request, context):
        """分页查询 API 列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAPIConfig(self, request, context):
        """查询单个 API 详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestAPIConnection(self, request, context):
        """测试 API 连接（含 WebSocket/HTTP 健康检查）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAPITestConfig(self, request, context):
        """停止 API 测试连接
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APITestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAPITest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPITest,
                    request_deserializer=api__test__service__pb2.CreateAPITestRequest.FromString,
                    response_serializer=api__test__service__pb2.CreateAPITestResponse.SerializeToString,
            ),
            'StartAPITest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAPITest,
                    request_deserializer=api__test__service__pb2.StartAPITestRequest.FromString,
                    response_serializer=api__test__service__pb2.StartAPITestResponse.SerializeToString,
            ),
            'StopAPITest': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAPITest,
                    request_deserializer=api__test__service__pb2.StopAPITestRequest.FromString,
                    response_serializer=api__test__service__pb2.StopAPITestResponse.SerializeToString,
            ),
            'GetAPITestStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPITestStatus,
                    request_deserializer=api__test__service__pb2.GetAPITestStatusRequest.FromString,
                    response_serializer=api__test__service__pb2.APITestStatusResponse.SerializeToString,
            ),
            'CreateAPIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIConfig,
                    request_deserializer=api__test__service__pb2.CreateAPIConfigRequest.FromString,
                    response_serializer=api__test__service__pb2.CreateAPIConfigResponse.SerializeToString,
            ),
            'UpdateAPIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAPIConfig,
                    request_deserializer=api__test__service__pb2.UpdateAPIConfigRequest.FromString,
                    response_serializer=api__test__service__pb2.UpdateAPIConfigResponse.SerializeToString,
            ),
            'DeleteAPIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAPIConfig,
                    request_deserializer=api__test__service__pb2.DeleteAPIConfigRequest.FromString,
                    response_serializer=api__test__service__pb2.DeleteAPIConfigResponse.SerializeToString,
            ),
            'ListAPIConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAPIConfigs,
                    request_deserializer=api__test__service__pb2.ListAPIConfigsRequest.FromString,
                    response_serializer=api__test__service__pb2.ListAPIConfigsResponse.SerializeToString,
            ),
            'GetAPIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPIConfig,
                    request_deserializer=api__test__service__pb2.GetAPIConfigRequest.FromString,
                    response_serializer=api__test__service__pb2.GetAPIConfigResponse.SerializeToString,
            ),
            'TestAPIConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TestAPIConnection,
                    request_deserializer=api__test__service__pb2.TestAPIConnectionRequest.FromString,
                    response_serializer=api__test__service__pb2.TestAPIConnectionResponse.SerializeToString,
            ),
            'StopAPITestConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAPITestConfig,
                    request_deserializer=api__test__service__pb2.StopAPITestConfigRequest.FromString,
                    response_serializer=api__test__service__pb2.StopAPITestConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_test_service.APITestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api_test_service.APITestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class APITestService:
    """===== API 测试服务 =====
    """

    @staticmethod
    def CreateAPITest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/CreateAPITest',
            api__test__service__pb2.CreateAPITestRequest.SerializeToString,
            api__test__service__pb2.CreateAPITestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAPITest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/StartAPITest',
            api__test__service__pb2.StartAPITestRequest.SerializeToString,
            api__test__service__pb2.StartAPITestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAPITest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/StopAPITest',
            api__test__service__pb2.StopAPITestRequest.SerializeToString,
            api__test__service__pb2.StopAPITestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAPITestStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/GetAPITestStatus',
            api__test__service__pb2.GetAPITestStatusRequest.SerializeToString,
            api__test__service__pb2.APITestStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/CreateAPIConfig',
            api__test__service__pb2.CreateAPIConfigRequest.SerializeToString,
            api__test__service__pb2.CreateAPIConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAPIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/UpdateAPIConfig',
            api__test__service__pb2.UpdateAPIConfigRequest.SerializeToString,
            api__test__service__pb2.UpdateAPIConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAPIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/DeleteAPIConfig',
            api__test__service__pb2.DeleteAPIConfigRequest.SerializeToString,
            api__test__service__pb2.DeleteAPIConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAPIConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/ListAPIConfigs',
            api__test__service__pb2.ListAPIConfigsRequest.SerializeToString,
            api__test__service__pb2.ListAPIConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAPIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/GetAPIConfig',
            api__test__service__pb2.GetAPIConfigRequest.SerializeToString,
            api__test__service__pb2.GetAPIConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestAPIConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/TestAPIConnection',
            api__test__service__pb2.TestAPIConnectionRequest.SerializeToString,
            api__test__service__pb2.TestAPIConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAPITestConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.APITestService/StopAPITestConfig',
            api__test__service__pb2.StopAPITestConfigRequest.SerializeToString,
            api__test__service__pb2.StopAPITestConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ApiRmsSplConfigServiceStub:
    """===== API RMS→SPL 映射配置服务（UC-0902 数字域灵敏度校准，与设备域 SPLConfigService 对称）=====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/CreateRmsSplMapping',
                request_serializer=api__test__service__pb2.CreateRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.CreateRmsSplMappingResponse.FromString,
                _registered_method=True)
        self.UpdateRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/UpdateRmsSplMapping',
                request_serializer=api__test__service__pb2.UpdateRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.UpdateRmsSplMappingResponse.FromString,
                _registered_method=True)
        self.DeleteRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/DeleteRmsSplMapping',
                request_serializer=api__test__service__pb2.DeleteRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.DeleteRmsSplMappingResponse.FromString,
                _registered_method=True)
        self.ListRmsSplMappings = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/ListRmsSplMappings',
                request_serializer=api__test__service__pb2.ListRmsSplMappingsRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.ListRmsSplMappingsResponse.FromString,
                _registered_method=True)
        self.GetRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/GetRmsSplMapping',
                request_serializer=api__test__service__pb2.GetRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.GetRmsSplMappingResponse.FromString,
                _registered_method=True)
        self.GetRmsSplMappingsByApi = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/GetRmsSplMappingsByApi',
                request_serializer=api__test__service__pb2.GetRmsSplMappingsByApiRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.GetRmsSplMappingsByApiResponse.FromString,
                _registered_method=True)
        self.CalibrateRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/CalibrateRmsSplMapping',
                request_serializer=api__test__service__pb2.CalibrateRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.CalibrateRmsSplMappingResponse.FromString,
                _registered_method=True)
        self.SetDefaultRmsSplMapping = channel.unary_unary(
                '/api_test_service.ApiRmsSplConfigService/SetDefaultRmsSplMapping',
                request_serializer=api__test__service__pb2.SetDefaultRmsSplMappingRequest.SerializeToString,
                response_deserializer=api__test__service__pb2.SetDefaultRmsSplMappingResponse.FromString,
                _registered_method=True)


class ApiRmsSplConfigServiceServicer:
    """===== API RMS→SPL 映射配置服务（UC-0902 数字域灵敏度校准，与设备域 SPLConfigService 对称）=====
    """

    def CreateRmsSplMapping(self, request, context):
        """创建映射
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRmsSplMapping(self, request, context):
        """更新映射
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRmsSplMapping(self, request, context):
        """删除映射（软删除）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRmsSplMappings(self, request, context):
        """分页查询映射列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRmsSplMapping(self, request, context):
        """查询单个映射详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRmsSplMappingsByApi(self, request, context):
        """按 API 查映射列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateRmsSplMapping(self, request, context):
        """执行校准（并发互斥：DistributedLock lock:spl:calibration:{api_id}）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultRmsSplMapping(self, request, context):
        """设为 API 当前默认映射（apis.rms_spl_mapping_id）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiRmsSplConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRmsSplMapping,
                    request_deserializer=api__test__service__pb2.CreateRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.CreateRmsSplMappingResponse.SerializeToString,
            ),
            'UpdateRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRmsSplMapping,
                    request_deserializer=api__test__service__pb2.UpdateRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.UpdateRmsSplMappingResponse.SerializeToString,
            ),
            'DeleteRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRmsSplMapping,
                    request_deserializer=api__test__service__pb2.DeleteRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.DeleteRmsSplMappingResponse.SerializeToString,
            ),
            'ListRmsSplMappings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRmsSplMappings,
                    request_deserializer=api__test__service__pb2.ListRmsSplMappingsRequest.FromString,
                    response_serializer=api__test__service__pb2.ListRmsSplMappingsResponse.SerializeToString,
            ),
            'GetRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRmsSplMapping,
                    request_deserializer=api__test__service__pb2.GetRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.GetRmsSplMappingResponse.SerializeToString,
            ),
            'GetRmsSplMappingsByApi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRmsSplMappingsByApi,
                    request_deserializer=api__test__service__pb2.GetRmsSplMappingsByApiRequest.FromString,
                    response_serializer=api__test__service__pb2.GetRmsSplMappingsByApiResponse.SerializeToString,
            ),
            'CalibrateRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateRmsSplMapping,
                    request_deserializer=api__test__service__pb2.CalibrateRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.CalibrateRmsSplMappingResponse.SerializeToString,
            ),
            'SetDefaultRmsSplMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultRmsSplMapping,
                    request_deserializer=api__test__service__pb2.SetDefaultRmsSplMappingRequest.FromString,
                    response_serializer=api__test__service__pb2.SetDefaultRmsSplMappingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_test_service.ApiRmsSplConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api_test_service.ApiRmsSplConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiRmsSplConfigService:
    """===== API RMS→SPL 映射配置服务（UC-0902 数字域灵敏度校准，与设备域 SPLConfigService 对称）=====
    """

    @staticmethod
    def CreateRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/CreateRmsSplMapping',
            api__test__service__pb2.CreateRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.CreateRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/UpdateRmsSplMapping',
            api__test__service__pb2.UpdateRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.UpdateRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/DeleteRmsSplMapping',
            api__test__service__pb2.DeleteRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.DeleteRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRmsSplMappings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/ListRmsSplMappings',
            api__test__service__pb2.ListRmsSplMappingsRequest.SerializeToString,
            api__test__service__pb2.ListRmsSplMappingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/GetRmsSplMapping',
            api__test__service__pb2.GetRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.GetRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRmsSplMappingsByApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/GetRmsSplMappingsByApi',
            api__test__service__pb2.GetRmsSplMappingsByApiRequest.SerializeToString,
            api__test__service__pb2.GetRmsSplMappingsByApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/CalibrateRmsSplMapping',
            api__test__service__pb2.CalibrateRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.CalibrateRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultRmsSplMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_test_service.ApiRmsSplConfigService/SetDefaultRmsSplMapping',
            api__test__service__pb2.SetDefaultRmsSplMappingRequest.SerializeToString,
            api__test__service__pb2.SetDefaultRmsSplMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
