# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_test_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'api_test_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi_test_service.proto\x12\x10\x61pi_test_service\"<\n\x14\x43reateAPITestRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x13\n\x0btest_config\x18\x02 \x01(\t\"G\n\x15\x43reateAPITestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"&\n\x13StartAPITestRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"F\n\x14StartAPITestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"%\n\x12StopAPITestRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"E\n\x13StopAPITestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"*\n\x17GetAPITestStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"G\n\x15\x41PITestStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x95\x03\n\x0e\x41PITestService\x12`\n\rCreateAPITest\x12&.api_test_service.CreateAPITestRequest\x1a\'.api_test_service.CreateAPITestResponse\x12]\n\x0cStartAPITest\x12%.api_test_service.StartAPITestRequest\x1a&.api_test_service.StartAPITestResponse\x12Z\n\x0bStopAPITest\x12$.api_test_service.StopAPITestRequest\x1a%.api_test_service.StopAPITestResponse\x12\x66\n\x10GetAPITestStatus\x12).api_test_service.GetAPITestStatusRequest\x1a\'.api_test_service.APITestStatusResponseB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_test_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_CREATEAPITESTREQUEST']._serialized_start=44
  _globals['_CREATEAPITESTREQUEST']._serialized_end=104
  _globals['_CREATEAPITESTRESPONSE']._serialized_start=106
  _globals['_CREATEAPITESTRESPONSE']._serialized_end=177
  _globals['_STARTAPITESTREQUEST']._serialized_start=179
  _globals['_STARTAPITESTREQUEST']._serialized_end=217
  _globals['_STARTAPITESTRESPONSE']._serialized_start=219
  _globals['_STARTAPITESTRESPONSE']._serialized_end=289
  _globals['_STOPAPITESTREQUEST']._serialized_start=291
  _globals['_STOPAPITESTREQUEST']._serialized_end=328
  _globals['_STOPAPITESTRESPONSE']._serialized_start=330
  _globals['_STOPAPITESTRESPONSE']._serialized_end=399
  _globals['_GETAPITESTSTATUSREQUEST']._serialized_start=401
  _globals['_GETAPITESTSTATUSREQUEST']._serialized_end=443
  _globals['_APITESTSTATUSRESPONSE']._serialized_start=445
  _globals['_APITESTSTATUSRESPONSE']._serialized_end=516
  _globals['_APITESTSERVICE']._serialized_start=519
  _globals['_APITESTSERVICE']._serialized_end=924
_builder.BuildServices(DESCRIPTOR, 'api_test_service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
