# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_service_pb2 as auth__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """===== 认证服务（用户管理 + 权限查询 + 认证校验）=====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/auth.AuthService/GetUser',
                request_serializer=auth__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/auth.AuthService/GetUserByUsername',
                request_serializer=auth__service__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetUserByOAuth = channel.unary_unary(
                '/auth.AuthService/GetUserByOAuth',
                request_serializer=auth__service__pb2.GetUserByOAuthRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/auth.AuthService/CreateUser',
                request_serializer=auth__service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UpdateLastLogin = channel.unary_unary(
                '/auth.AuthService/UpdateLastLogin',
                request_serializer=auth__service__pb2.UpdateLastLoginRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetUserPermissions = channel.unary_unary(
                '/auth.AuthService/GetUserPermissions',
                request_serializer=auth__service__pb2.GetUserPermissionsRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ListRoles = channel.unary_unary(
                '/auth.AuthService/ListRoles',
                request_serializer=auth__service__pb2.ListRolesRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/auth.AuthService/ListUsers',
                request_serializer=auth__service__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UpdateUserStatus = channel.unary_unary(
                '/auth.AuthService/UpdateUserStatus',
                request_serializer=auth__service__pb2.UpdateUserStatusRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GrantPermission = channel.unary_unary(
                '/auth.AuthService/GrantPermission',
                request_serializer=auth__service__pb2.GrantPermissionRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.RevokePermission = channel.unary_unary(
                '/auth.AuthService/RevokePermission',
                request_serializer=auth__service__pb2.RevokePermissionRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/auth.AuthService/DeleteUser',
                request_serializer=auth__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/auth.AuthService/UpdateUser',
                request_serializer=auth__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.SetUserRole = channel.unary_unary(
                '/auth.AuthService/SetUserRole',
                request_serializer=auth__service__pb2.SetUserRoleRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetRole = channel.unary_unary(
                '/auth.AuthService/GetRole',
                request_serializer=auth__service__pb2.GetRoleRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/auth.AuthService/CreateRole',
                request_serializer=auth__service__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UpdateRole = channel.unary_unary(
                '/auth.AuthService/UpdateRole',
                request_serializer=auth__service__pb2.UpdateRoleRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.SetRolePermissions = channel.unary_unary(
                '/auth.AuthService/SetRolePermissions',
                request_serializer=auth__service__pb2.SetRolePermissionsRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/auth.AuthService/DeleteRole',
                request_serializer=auth__service__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ListPermissions = channel.unary_unary(
                '/auth.AuthService/ListPermissions',
                request_serializer=auth__service__pb2.ListPermissionsRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.LoginWithPassword = channel.unary_unary(
                '/auth.AuthService/LoginWithPassword',
                request_serializer=auth__service__pb2.LoginWithPasswordRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ListOAuthProviders = channel.unary_unary(
                '/auth.AuthService/ListOAuthProviders',
                request_serializer=auth__service__pb2.ListOAuthProvidersRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetOAuthProvider = channel.unary_unary(
                '/auth.AuthService/GetOAuthProvider',
                request_serializer=auth__service__pb2.GetOAuthProviderRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetOAuthProviderBySlug = channel.unary_unary(
                '/auth.AuthService/GetOAuthProviderBySlug',
                request_serializer=auth__service__pb2.GetOAuthProviderBySlugRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ListEnabledOAuthProviders = channel.unary_unary(
                '/auth.AuthService/ListEnabledOAuthProviders',
                request_serializer=auth__service__pb2.ListEnabledOAuthProvidersRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CreateOAuthProvider = channel.unary_unary(
                '/auth.AuthService/CreateOAuthProvider',
                request_serializer=auth__service__pb2.CreateOAuthProviderRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UpdateOAuthProvider = channel.unary_unary(
                '/auth.AuthService/UpdateOAuthProvider',
                request_serializer=auth__service__pb2.UpdateOAuthProviderRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.DeleteOAuthProvider = channel.unary_unary(
                '/auth.AuthService/DeleteOAuthProvider',
                request_serializer=auth__service__pb2.DeleteOAuthProviderRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """===== 认证服务（用户管理 + 权限查询 + 认证校验）=====
    """

    def GetUser(self, request, context):
        """按 ID 获取用户（含角色名、权限列表）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """按用户名获取用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByOAuth(self, request, context):
        """按 OAuth 提供商 + 外部 ID 获取用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """创建用户（OAuth 或本地注册），返回新用户 ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLastLogin(self, request, context):
        """更新最后登录时间/IP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPermissions(self, request, context):
        """获取用户权限码列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoles(self, request, context):
        """列出所有角色
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """分页列出用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserStatus(self, request, context):
        """更新用户状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermission(self, request, context):
        """授予权限
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokePermission(self, request, context):
        """撤销权限
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """软删除用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """更新用户资料（username/email/status/password，空串字段不修改）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserRole(self, request, context):
        """设置用户角色
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRole(self, request, context):
        """===== 角色与权限管理 =====
        按角色 ID 获取角色（含权限码列表）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """创建角色（name/description/repeated permission_codes）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """更新角色信息（name/description 空串=不修改）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRolePermissions(self, request, context):
        """全量替换角色权限（repeated permission_codes）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """删除角色（连带 role_permissions）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPermissions(self, request, context):
        """列出全部权限点
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginWithPassword(self, request, context):
        """===== 登录体系改造（INT-51）=====
        用户名+密码登录校验（服务端 bcrypt 校验 password_hash，成功返回用户数据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOAuthProviders(self, request, context):
        """自定义 OAuth 提供方管理：全部（管理端，含禁用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOAuthProvider(self, request, context):
        """按 ID 获取提供方
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOAuthProviderBySlug(self, request, context):
        """按 slug 获取提供方（登录链路）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnabledOAuthProviders(self, request, context):
        """已启用提供方列表（登录页动态渲染，公开）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOAuthProvider(self, request, context):
        """创建提供方
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOAuthProvider(self, request, context):
        """更新提供方（空串字段=不修改；client_secret 空串=保留原值）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOAuthProvider(self, request, context):
        """删除提供方
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__service__pb2.GetUserRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=auth__service__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetUserByOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByOAuth,
                    request_deserializer=auth__service__pb2.GetUserByOAuthRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=auth__service__pb2.CreateUserRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'UpdateLastLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLastLogin,
                    request_deserializer=auth__service__pb2.UpdateLastLoginRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetUserPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPermissions,
                    request_deserializer=auth__service__pb2.GetUserPermissionsRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'ListRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoles,
                    request_deserializer=auth__service__pb2.ListRolesRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=auth__service__pb2.ListUsersRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserStatus,
                    request_deserializer=auth__service__pb2.UpdateUserStatusRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GrantPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantPermission,
                    request_deserializer=auth__service__pb2.GrantPermissionRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'RevokePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokePermission,
                    request_deserializer=auth__service__pb2.RevokePermissionRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=auth__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=auth__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'SetUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserRole,
                    request_deserializer=auth__service__pb2.SetUserRoleRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRole,
                    request_deserializer=auth__service__pb2.GetRoleRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=auth__service__pb2.CreateRoleRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=auth__service__pb2.UpdateRoleRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'SetRolePermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRolePermissions,
                    request_deserializer=auth__service__pb2.SetRolePermissionsRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=auth__service__pb2.DeleteRoleRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'ListPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPermissions,
                    request_deserializer=auth__service__pb2.ListPermissionsRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'LoginWithPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginWithPassword,
                    request_deserializer=auth__service__pb2.LoginWithPasswordRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'ListOAuthProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOAuthProviders,
                    request_deserializer=auth__service__pb2.ListOAuthProvidersRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetOAuthProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOAuthProvider,
                    request_deserializer=auth__service__pb2.GetOAuthProviderRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'GetOAuthProviderBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOAuthProviderBySlug,
                    request_deserializer=auth__service__pb2.GetOAuthProviderBySlugRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'ListEnabledOAuthProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnabledOAuthProviders,
                    request_deserializer=auth__service__pb2.ListEnabledOAuthProvidersRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'CreateOAuthProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOAuthProvider,
                    request_deserializer=auth__service__pb2.CreateOAuthProviderRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'UpdateOAuthProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOAuthProvider,
                    request_deserializer=auth__service__pb2.UpdateOAuthProviderRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'DeleteOAuthProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOAuthProvider,
                    request_deserializer=auth__service__pb2.DeleteOAuthProviderRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """===== 认证服务（用户管理 + 权限查询 + 认证校验）=====
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUser',
            auth__service__pb2.GetUserRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserByUsername',
            auth__service__pb2.GetUserByUsernameRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserByOAuth',
            auth__service__pb2.GetUserByOAuthRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateUser',
            auth__service__pb2.CreateUserRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLastLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateLastLogin',
            auth__service__pb2.UpdateLastLoginRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserPermissions',
            auth__service__pb2.GetUserPermissionsRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListRoles',
            auth__service__pb2.ListRolesRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListUsers',
            auth__service__pb2.ListUsersRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateUserStatus',
            auth__service__pb2.UpdateUserStatusRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GrantPermission',
            auth__service__pb2.GrantPermissionRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RevokePermission',
            auth__service__pb2.RevokePermissionRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteUser',
            auth__service__pb2.DeleteUserRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateUser',
            auth__service__pb2.UpdateUserRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SetUserRole',
            auth__service__pb2.SetUserRoleRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetRole',
            auth__service__pb2.GetRoleRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateRole',
            auth__service__pb2.CreateRoleRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateRole',
            auth__service__pb2.UpdateRoleRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRolePermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SetRolePermissions',
            auth__service__pb2.SetRolePermissionsRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteRole',
            auth__service__pb2.DeleteRoleRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListPermissions',
            auth__service__pb2.ListPermissionsRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginWithPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/LoginWithPassword',
            auth__service__pb2.LoginWithPasswordRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOAuthProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListOAuthProviders',
            auth__service__pb2.ListOAuthProvidersRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOAuthProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetOAuthProvider',
            auth__service__pb2.GetOAuthProviderRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOAuthProviderBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetOAuthProviderBySlug',
            auth__service__pb2.GetOAuthProviderBySlugRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnabledOAuthProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListEnabledOAuthProviders',
            auth__service__pb2.ListEnabledOAuthProvidersRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOAuthProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateOAuthProvider',
            auth__service__pb2.CreateOAuthProviderRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOAuthProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateOAuthProvider',
            auth__service__pb2.UpdateOAuthProviderRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOAuthProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteOAuthProvider',
            auth__service__pb2.DeleteOAuthProviderRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
