# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_service_pb2 as device__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """===== 设备驱动服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDriver = channel.unary_unary(
                '/device_service.DeviceService/CreateDriver',
                request_serializer=device__service__pb2.CreateDriverRequest.SerializeToString,
                response_deserializer=device__service__pb2.CreateDriverResponse.FromString,
                _registered_method=True)
        self.DestroyDriver = channel.unary_unary(
                '/device_service.DeviceService/DestroyDriver',
                request_serializer=device__service__pb2.DestroyDriverRequest.SerializeToString,
                response_deserializer=device__service__pb2.DestroyDriverResponse.FromString,
                _registered_method=True)
        self.RegisterTaskEvents = channel.unary_unary(
                '/device_service.DeviceService/RegisterTaskEvents',
                request_serializer=device__service__pb2.RegisterTaskEventsRequest.SerializeToString,
                response_deserializer=device__service__pb2.RegisterTaskEventsResponse.FromString,
                _registered_method=True)
        self.UnregisterTaskEvents = channel.unary_unary(
                '/device_service.DeviceService/UnregisterTaskEvents',
                request_serializer=device__service__pb2.UnregisterTaskEventsRequest.SerializeToString,
                response_deserializer=device__service__pb2.UnregisterTaskEventsResponse.FromString,
                _registered_method=True)
        self.GetTaskEvents = channel.unary_unary(
                '/device_service.DeviceService/GetTaskEvents',
                request_serializer=device__service__pb2.GetTaskEventsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetTaskEventsResponse.FromString,
                _registered_method=True)
        self.DriverScan = channel.unary_unary(
                '/device_service.DeviceService/DriverScan',
                request_serializer=device__service__pb2.DriverScanRequest.SerializeToString,
                response_deserializer=device__service__pb2.DriverScanResponse.FromString,
                _registered_method=True)
        self.DriverUnlock = channel.unary_unary(
                '/device_service.DeviceService/DriverUnlock',
                request_serializer=device__service__pb2.DriverUnlockRequest.SerializeToString,
                response_deserializer=device__service__pb2.DriverUnlockResponse.FromString,
                _registered_method=True)
        self.GetMockMode = channel.unary_unary(
                '/device_service.DeviceService/GetMockMode',
                request_serializer=device__service__pb2.GetMockModeRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetMockModeResponse.FromString,
                _registered_method=True)
        self.SetMockMode = channel.unary_unary(
                '/device_service.DeviceService/SetMockMode',
                request_serializer=device__service__pb2.SetMockModeRequest.SerializeToString,
                response_deserializer=device__service__pb2.SetMockModeResponse.FromString,
                _registered_method=True)
        self.GetDriverNameByKeywords = channel.unary_unary(
                '/device_service.DeviceService/GetDriverNameByKeywords',
                request_serializer=device__service__pb2.GetDriverNameByKeywordsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDriverNameByKeywordsResponse.FromString,
                _registered_method=True)
        self.GetRegisteredKeywords = channel.unary_unary(
                '/device_service.DeviceService/GetRegisteredKeywords',
                request_serializer=device__service__pb2.GetRegisteredKeywordsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetRegisteredKeywordsResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """===== 设备驱动服务 =====
    """

    def CreateDriver(self, request, context):
        """创建设备驱动（连接设备）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyDriver(self, request, context):
        """销毁设备驱动
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTaskEvents(self, request, context):
        """注册任务事件回调
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterTaskEvents(self, request, context):
        """注销任务事件回调
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskEvents(self, request, context):
        """获取任务事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverScan(self, request, context):
        """扫描设备
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverUnlock(self, request, context):
        """解锁设备
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMockMode(self, request, context):
        """获取 mock 模式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMockMode(self, request, context):
        """设置 mock 模式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriverNameByKeywords(self, request, context):
        """按关键词获取驱动名
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisteredKeywords(self, request, context):
        """获取已注册关键词
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDriver,
                    request_deserializer=device__service__pb2.CreateDriverRequest.FromString,
                    response_serializer=device__service__pb2.CreateDriverResponse.SerializeToString,
            ),
            'DestroyDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyDriver,
                    request_deserializer=device__service__pb2.DestroyDriverRequest.FromString,
                    response_serializer=device__service__pb2.DestroyDriverResponse.SerializeToString,
            ),
            'RegisterTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTaskEvents,
                    request_deserializer=device__service__pb2.RegisterTaskEventsRequest.FromString,
                    response_serializer=device__service__pb2.RegisterTaskEventsResponse.SerializeToString,
            ),
            'UnregisterTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterTaskEvents,
                    request_deserializer=device__service__pb2.UnregisterTaskEventsRequest.FromString,
                    response_serializer=device__service__pb2.UnregisterTaskEventsResponse.SerializeToString,
            ),
            'GetTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskEvents,
                    request_deserializer=device__service__pb2.GetTaskEventsRequest.FromString,
                    response_serializer=device__service__pb2.GetTaskEventsResponse.SerializeToString,
            ),
            'DriverScan': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverScan,
                    request_deserializer=device__service__pb2.DriverScanRequest.FromString,
                    response_serializer=device__service__pb2.DriverScanResponse.SerializeToString,
            ),
            'DriverUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverUnlock,
                    request_deserializer=device__service__pb2.DriverUnlockRequest.FromString,
                    response_serializer=device__service__pb2.DriverUnlockResponse.SerializeToString,
            ),
            'GetMockMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMockMode,
                    request_deserializer=device__service__pb2.GetMockModeRequest.FromString,
                    response_serializer=device__service__pb2.GetMockModeResponse.SerializeToString,
            ),
            'SetMockMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMockMode,
                    request_deserializer=device__service__pb2.SetMockModeRequest.FromString,
                    response_serializer=device__service__pb2.SetMockModeResponse.SerializeToString,
            ),
            'GetDriverNameByKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriverNameByKeywords,
                    request_deserializer=device__service__pb2.GetDriverNameByKeywordsRequest.FromString,
                    response_serializer=device__service__pb2.GetDriverNameByKeywordsResponse.SerializeToString,
            ),
            'GetRegisteredKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisteredKeywords,
                    request_deserializer=device__service__pb2.GetRegisteredKeywordsRequest.FromString,
                    response_serializer=device__service__pb2.GetRegisteredKeywordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """===== 设备驱动服务 =====
    """

    @staticmethod
    def CreateDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/CreateDriver',
            device__service__pb2.CreateDriverRequest.SerializeToString,
            device__service__pb2.CreateDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/DestroyDriver',
            device__service__pb2.DestroyDriverRequest.SerializeToString,
            device__service__pb2.DestroyDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/RegisterTaskEvents',
            device__service__pb2.RegisterTaskEventsRequest.SerializeToString,
            device__service__pb2.RegisterTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/UnregisterTaskEvents',
            device__service__pb2.UnregisterTaskEventsRequest.SerializeToString,
            device__service__pb2.UnregisterTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/GetTaskEvents',
            device__service__pb2.GetTaskEventsRequest.SerializeToString,
            device__service__pb2.GetTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/DriverScan',
            device__service__pb2.DriverScanRequest.SerializeToString,
            device__service__pb2.DriverScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/DriverUnlock',
            device__service__pb2.DriverUnlockRequest.SerializeToString,
            device__service__pb2.DriverUnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMockMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/GetMockMode',
            device__service__pb2.GetMockModeRequest.SerializeToString,
            device__service__pb2.GetMockModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMockMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/SetMockMode',
            device__service__pb2.SetMockModeRequest.SerializeToString,
            device__service__pb2.SetMockModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriverNameByKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/GetDriverNameByKeywords',
            device__service__pb2.GetDriverNameByKeywordsRequest.SerializeToString,
            device__service__pb2.GetDriverNameByKeywordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegisteredKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceService/GetRegisteredKeywords',
            device__service__pb2.GetRegisteredKeywordsRequest.SerializeToString,
            device__service__pb2.GetRegisteredKeywordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceResultServiceStub:
    """===== 设备结果采集服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectResult = channel.unary_unary(
                '/device_service.DeviceResultService/CollectResult',
                request_serializer=device__service__pb2.CollectResultRequest.SerializeToString,
                response_deserializer=device__service__pb2.CollectResultResponse.FromString,
                _registered_method=True)
        self.ReextractResult = channel.unary_unary(
                '/device_service.DeviceResultService/ReextractResult',
                request_serializer=device__service__pb2.ReextractResultRequest.SerializeToString,
                response_deserializer=device__service__pb2.ReextractResultResponse.FromString,
                _registered_method=True)


class DeviceResultServiceServicer:
    """===== 设备结果采集服务 =====
    """

    def CollectResult(self, request, context):
        """采集设备结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReextractResult(self, request, context):
        """重新提取设备结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceResultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectResult': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectResult,
                    request_deserializer=device__service__pb2.CollectResultRequest.FromString,
                    response_serializer=device__service__pb2.CollectResultResponse.SerializeToString,
            ),
            'ReextractResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReextractResult,
                    request_deserializer=device__service__pb2.ReextractResultRequest.FromString,
                    response_serializer=device__service__pb2.ReextractResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.DeviceResultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.DeviceResultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceResultService:
    """===== 设备结果采集服务 =====
    """

    @staticmethod
    def CollectResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceResultService/CollectResult',
            device__service__pb2.CollectResultRequest.SerializeToString,
            device__service__pb2.CollectResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReextractResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceResultService/ReextractResult',
            device__service__pb2.ReextractResultRequest.SerializeToString,
            device__service__pb2.ReextractResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnvDeviceServiceStub:
    """===== 环境设备服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlEnvDevice = channel.unary_unary(
                '/device_service.EnvDeviceService/ControlEnvDevice',
                request_serializer=device__service__pb2.ControlEnvDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.ControlEnvDeviceResponse.FromString,
                _registered_method=True)


class EnvDeviceServiceServicer:
    """===== 环境设备服务 =====
    """

    def ControlEnvDevice(self, request, context):
        """控制环境设备（导轨旋转等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlEnvDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlEnvDevice,
                    request_deserializer=device__service__pb2.ControlEnvDeviceRequest.FromString,
                    response_serializer=device__service__pb2.ControlEnvDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.EnvDeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.EnvDeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvDeviceService:
    """===== 环境设备服务 =====
    """

    @staticmethod
    def ControlEnvDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.EnvDeviceService/ControlEnvDevice',
            device__service__pb2.ControlEnvDeviceRequest.SerializeToString,
            device__service__pb2.ControlEnvDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceConfigServiceStub:
    """===== 设备管理 CRUD 服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDevice = channel.unary_unary(
                '/device_service.DeviceConfigService/CreateDevice',
                request_serializer=device__service__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.CreateDeviceResponse.FromString,
                _registered_method=True)
        self.UpdateDevice = channel.unary_unary(
                '/device_service.DeviceConfigService/UpdateDevice',
                request_serializer=device__service__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.UpdateDeviceResponse.FromString,
                _registered_method=True)
        self.DeleteDevice = channel.unary_unary(
                '/device_service.DeviceConfigService/DeleteDevice',
                request_serializer=device__service__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.DeleteDeviceResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/device_service.DeviceConfigService/ListDevices',
                request_serializer=device__service__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.GetDevice = channel.unary_unary(
                '/device_service.DeviceConfigService/GetDevice',
                request_serializer=device__service__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDeviceResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatuses = channel.unary_unary(
                '/device_service.DeviceConfigService/GetDeviceStatuses',
                request_serializer=device__service__pb2.GetDeviceStatusesRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDeviceStatusesResponse.FromString,
                _registered_method=True)
        self.ScanPhysicalDevices = channel.unary_unary(
                '/device_service.DeviceConfigService/ScanPhysicalDevices',
                request_serializer=device__service__pb2.ScanPhysicalDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.ScanPhysicalDevicesResponse.FromString,
                _registered_method=True)
        self.TestDevice = channel.unary_unary(
                '/device_service.DeviceConfigService/TestDevice',
                request_serializer=device__service__pb2.TestDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.TestDeviceResponse.FromString,
                _registered_method=True)
        self.StopDeviceTest = channel.unary_unary(
                '/device_service.DeviceConfigService/StopDeviceTest',
                request_serializer=device__service__pb2.StopDeviceTestRequest.SerializeToString,
                response_deserializer=device__service__pb2.StopDeviceTestResponse.FromString,
                _registered_method=True)
        self.GetDriverKeywords = channel.unary_unary(
                '/device_service.DeviceConfigService/GetDriverKeywords',
                request_serializer=device__service__pb2.GetDriverKeywordsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDriverKeywordsResponse.FromString,
                _registered_method=True)
        self.HealthCheckDevices = channel.unary_unary(
                '/device_service.DeviceConfigService/HealthCheckDevices',
                request_serializer=device__service__pb2.HealthCheckDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.HealthCheckDevicesResponse.FromString,
                _registered_method=True)
        self.GetAvailableSerials = channel.unary_unary(
                '/device_service.DeviceConfigService/GetAvailableSerials',
                request_serializer=device__service__pb2.GetAvailableSerialsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetAvailableSerialsResponse.FromString,
                _registered_method=True)


class DeviceConfigServiceServicer:
    """===== 设备管理 CRUD 服务 =====
    """

    def CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPhysicalDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDeviceTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriverKeywords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheckDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableSerials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=device__service__pb2.CreateDeviceRequest.FromString,
                    response_serializer=device__service__pb2.CreateDeviceResponse.SerializeToString,
            ),
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=device__service__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=device__service__pb2.UpdateDeviceResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=device__service__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=device__service__pb2.DeleteDeviceResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__service__pb2.ListDevicesRequest.FromString,
                    response_serializer=device__service__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=device__service__pb2.GetDeviceRequest.FromString,
                    response_serializer=device__service__pb2.GetDeviceResponse.SerializeToString,
            ),
            'GetDeviceStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatuses,
                    request_deserializer=device__service__pb2.GetDeviceStatusesRequest.FromString,
                    response_serializer=device__service__pb2.GetDeviceStatusesResponse.SerializeToString,
            ),
            'ScanPhysicalDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPhysicalDevices,
                    request_deserializer=device__service__pb2.ScanPhysicalDevicesRequest.FromString,
                    response_serializer=device__service__pb2.ScanPhysicalDevicesResponse.SerializeToString,
            ),
            'TestDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.TestDevice,
                    request_deserializer=device__service__pb2.TestDeviceRequest.FromString,
                    response_serializer=device__service__pb2.TestDeviceResponse.SerializeToString,
            ),
            'StopDeviceTest': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDeviceTest,
                    request_deserializer=device__service__pb2.StopDeviceTestRequest.FromString,
                    response_serializer=device__service__pb2.StopDeviceTestResponse.SerializeToString,
            ),
            'GetDriverKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriverKeywords,
                    request_deserializer=device__service__pb2.GetDriverKeywordsRequest.FromString,
                    response_serializer=device__service__pb2.GetDriverKeywordsResponse.SerializeToString,
            ),
            'HealthCheckDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheckDevices,
                    request_deserializer=device__service__pb2.HealthCheckDevicesRequest.FromString,
                    response_serializer=device__service__pb2.HealthCheckDevicesResponse.SerializeToString,
            ),
            'GetAvailableSerials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSerials,
                    request_deserializer=device__service__pb2.GetAvailableSerialsRequest.FromString,
                    response_serializer=device__service__pb2.GetAvailableSerialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.DeviceConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.DeviceConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceConfigService:
    """===== 设备管理 CRUD 服务 =====
    """

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/CreateDevice',
            device__service__pb2.CreateDeviceRequest.SerializeToString,
            device__service__pb2.CreateDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/UpdateDevice',
            device__service__pb2.UpdateDeviceRequest.SerializeToString,
            device__service__pb2.UpdateDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/DeleteDevice',
            device__service__pb2.DeleteDeviceRequest.SerializeToString,
            device__service__pb2.DeleteDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/ListDevices',
            device__service__pb2.ListDevicesRequest.SerializeToString,
            device__service__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/GetDevice',
            device__service__pb2.GetDeviceRequest.SerializeToString,
            device__service__pb2.GetDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/GetDeviceStatuses',
            device__service__pb2.GetDeviceStatusesRequest.SerializeToString,
            device__service__pb2.GetDeviceStatusesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPhysicalDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/ScanPhysicalDevices',
            device__service__pb2.ScanPhysicalDevicesRequest.SerializeToString,
            device__service__pb2.ScanPhysicalDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/TestDevice',
            device__service__pb2.TestDeviceRequest.SerializeToString,
            device__service__pb2.TestDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopDeviceTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/StopDeviceTest',
            device__service__pb2.StopDeviceTestRequest.SerializeToString,
            device__service__pb2.StopDeviceTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriverKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/GetDriverKeywords',
            device__service__pb2.GetDriverKeywordsRequest.SerializeToString,
            device__service__pb2.GetDriverKeywordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheckDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/HealthCheckDevices',
            device__service__pb2.HealthCheckDevicesRequest.SerializeToString,
            device__service__pb2.HealthCheckDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableSerials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.DeviceConfigService/GetAvailableSerials',
            device__service__pb2.GetAvailableSerialsRequest.SerializeToString,
            device__service__pb2.GetAvailableSerialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaybackConfigServiceStub:
    """===== 播放设备 CRUD 服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePlaybackDevice = channel.unary_unary(
                '/device_service.PlaybackConfigService/CreatePlaybackDevice',
                request_serializer=device__service__pb2.CreatePlaybackDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.CreatePlaybackDeviceResponse.FromString,
                _registered_method=True)
        self.UpdatePlaybackDevice = channel.unary_unary(
                '/device_service.PlaybackConfigService/UpdatePlaybackDevice',
                request_serializer=device__service__pb2.UpdatePlaybackDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.UpdatePlaybackDeviceResponse.FromString,
                _registered_method=True)
        self.DeletePlaybackDevice = channel.unary_unary(
                '/device_service.PlaybackConfigService/DeletePlaybackDevice',
                request_serializer=device__service__pb2.DeletePlaybackDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.DeletePlaybackDeviceResponse.FromString,
                _registered_method=True)
        self.ListPlaybackDevices = channel.unary_unary(
                '/device_service.PlaybackConfigService/ListPlaybackDevices',
                request_serializer=device__service__pb2.ListPlaybackDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.ListPlaybackDevicesResponse.FromString,
                _registered_method=True)
        self.GetPlaybackDevice = channel.unary_unary(
                '/device_service.PlaybackConfigService/GetPlaybackDevice',
                request_serializer=device__service__pb2.GetPlaybackDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetPlaybackDeviceResponse.FromString,
                _registered_method=True)
        self.ScanPlaybackDevices = channel.unary_unary(
                '/device_service.PlaybackConfigService/ScanPlaybackDevices',
                request_serializer=device__service__pb2.ScanPlaybackDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.ScanPlaybackDevicesResponse.FromString,
                _registered_method=True)
        self.CheckPlaybackStatus = channel.unary_unary(
                '/device_service.PlaybackConfigService/CheckPlaybackStatus',
                request_serializer=device__service__pb2.CheckPlaybackStatusRequest.SerializeToString,
                response_deserializer=device__service__pb2.CheckPlaybackStatusResponse.FromString,
                _registered_method=True)
        self.AssociateSPL = channel.unary_unary(
                '/device_service.PlaybackConfigService/AssociateSPL',
                request_serializer=device__service__pb2.AssociateSPLRequest.SerializeToString,
                response_deserializer=device__service__pb2.AssociateSPLResponse.FromString,
                _registered_method=True)
        self.TestPlaybackDevice = channel.unary_unary(
                '/device_service.PlaybackConfigService/TestPlaybackDevice',
                request_serializer=device__service__pb2.TestPlaybackDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.TestPlaybackDeviceResponse.FromString,
                _registered_method=True)
        self.StopPlaybackTest = channel.unary_unary(
                '/device_service.PlaybackConfigService/StopPlaybackTest',
                request_serializer=device__service__pb2.StopPlaybackTestRequest.SerializeToString,
                response_deserializer=device__service__pb2.StopPlaybackTestResponse.FromString,
                _registered_method=True)


class PlaybackConfigServiceServicer:
    """===== 播放设备 CRUD 服务 =====
    """

    def CreatePlaybackDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaybackDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaybackDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaybackDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaybackDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPlaybackDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPlaybackStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssociateSPL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPlaybackDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPlaybackTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePlaybackDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaybackDevice,
                    request_deserializer=device__service__pb2.CreatePlaybackDeviceRequest.FromString,
                    response_serializer=device__service__pb2.CreatePlaybackDeviceResponse.SerializeToString,
            ),
            'UpdatePlaybackDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaybackDevice,
                    request_deserializer=device__service__pb2.UpdatePlaybackDeviceRequest.FromString,
                    response_serializer=device__service__pb2.UpdatePlaybackDeviceResponse.SerializeToString,
            ),
            'DeletePlaybackDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaybackDevice,
                    request_deserializer=device__service__pb2.DeletePlaybackDeviceRequest.FromString,
                    response_serializer=device__service__pb2.DeletePlaybackDeviceResponse.SerializeToString,
            ),
            'ListPlaybackDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaybackDevices,
                    request_deserializer=device__service__pb2.ListPlaybackDevicesRequest.FromString,
                    response_serializer=device__service__pb2.ListPlaybackDevicesResponse.SerializeToString,
            ),
            'GetPlaybackDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackDevice,
                    request_deserializer=device__service__pb2.GetPlaybackDeviceRequest.FromString,
                    response_serializer=device__service__pb2.GetPlaybackDeviceResponse.SerializeToString,
            ),
            'ScanPlaybackDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPlaybackDevices,
                    request_deserializer=device__service__pb2.ScanPlaybackDevicesRequest.FromString,
                    response_serializer=device__service__pb2.ScanPlaybackDevicesResponse.SerializeToString,
            ),
            'CheckPlaybackStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPlaybackStatus,
                    request_deserializer=device__service__pb2.CheckPlaybackStatusRequest.FromString,
                    response_serializer=device__service__pb2.CheckPlaybackStatusResponse.SerializeToString,
            ),
            'AssociateSPL': grpc.unary_unary_rpc_method_handler(
                    servicer.AssociateSPL,
                    request_deserializer=device__service__pb2.AssociateSPLRequest.FromString,
                    response_serializer=device__service__pb2.AssociateSPLResponse.SerializeToString,
            ),
            'TestPlaybackDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPlaybackDevice,
                    request_deserializer=device__service__pb2.TestPlaybackDeviceRequest.FromString,
                    response_serializer=device__service__pb2.TestPlaybackDeviceResponse.SerializeToString,
            ),
            'StopPlaybackTest': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPlaybackTest,
                    request_deserializer=device__service__pb2.StopPlaybackTestRequest.FromString,
                    response_serializer=device__service__pb2.StopPlaybackTestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.PlaybackConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.PlaybackConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackConfigService:
    """===== 播放设备 CRUD 服务 =====
    """

    @staticmethod
    def CreatePlaybackDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/CreatePlaybackDevice',
            device__service__pb2.CreatePlaybackDeviceRequest.SerializeToString,
            device__service__pb2.CreatePlaybackDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaybackDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/UpdatePlaybackDevice',
            device__service__pb2.UpdatePlaybackDeviceRequest.SerializeToString,
            device__service__pb2.UpdatePlaybackDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaybackDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/DeletePlaybackDevice',
            device__service__pb2.DeletePlaybackDeviceRequest.SerializeToString,
            device__service__pb2.DeletePlaybackDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaybackDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/ListPlaybackDevices',
            device__service__pb2.ListPlaybackDevicesRequest.SerializeToString,
            device__service__pb2.ListPlaybackDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaybackDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/GetPlaybackDevice',
            device__service__pb2.GetPlaybackDeviceRequest.SerializeToString,
            device__service__pb2.GetPlaybackDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPlaybackDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/ScanPlaybackDevices',
            device__service__pb2.ScanPlaybackDevicesRequest.SerializeToString,
            device__service__pb2.ScanPlaybackDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPlaybackStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/CheckPlaybackStatus',
            device__service__pb2.CheckPlaybackStatusRequest.SerializeToString,
            device__service__pb2.CheckPlaybackStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssociateSPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/AssociateSPL',
            device__service__pb2.AssociateSPLRequest.SerializeToString,
            device__service__pb2.AssociateSPLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPlaybackDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/TestPlaybackDevice',
            device__service__pb2.TestPlaybackDeviceRequest.SerializeToString,
            device__service__pb2.TestPlaybackDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPlaybackTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.PlaybackConfigService/StopPlaybackTest',
            device__service__pb2.StopPlaybackTestRequest.SerializeToString,
            device__service__pb2.StopPlaybackTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SPLConfigServiceStub:
    """===== SPL 映射 CRUD 服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSPLMapping = channel.unary_unary(
                '/device_service.SPLConfigService/CreateSPLMapping',
                request_serializer=device__service__pb2.CreateSPLMappingRequest.SerializeToString,
                response_deserializer=device__service__pb2.CreateSPLMappingResponse.FromString,
                _registered_method=True)
        self.UpdateSPLMapping = channel.unary_unary(
                '/device_service.SPLConfigService/UpdateSPLMapping',
                request_serializer=device__service__pb2.UpdateSPLMappingRequest.SerializeToString,
                response_deserializer=device__service__pb2.UpdateSPLMappingResponse.FromString,
                _registered_method=True)
        self.DeleteSPLMapping = channel.unary_unary(
                '/device_service.SPLConfigService/DeleteSPLMapping',
                request_serializer=device__service__pb2.DeleteSPLMappingRequest.SerializeToString,
                response_deserializer=device__service__pb2.DeleteSPLMappingResponse.FromString,
                _registered_method=True)
        self.ListSPLMappings = channel.unary_unary(
                '/device_service.SPLConfigService/ListSPLMappings',
                request_serializer=device__service__pb2.ListSPLMappingsRequest.SerializeToString,
                response_deserializer=device__service__pb2.ListSPLMappingsResponse.FromString,
                _registered_method=True)
        self.GetSPLMapping = channel.unary_unary(
                '/device_service.SPLConfigService/GetSPLMapping',
                request_serializer=device__service__pb2.GetSPLMappingRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetSPLMappingResponse.FromString,
                _registered_method=True)
        self.GetSPLHistory = channel.unary_unary(
                '/device_service.SPLConfigService/GetSPLHistory',
                request_serializer=device__service__pb2.GetSPLHistoryRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetSPLHistoryResponse.FromString,
                _registered_method=True)
        self.GetSPLCalibrationData = channel.unary_unary(
                '/device_service.SPLConfigService/GetSPLCalibrationData',
                request_serializer=device__service__pb2.GetSPLCalibrationDataRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetSPLCalibrationDataResponse.FromString,
                _registered_method=True)
        self.GetSPLStats = channel.unary_unary(
                '/device_service.SPLConfigService/GetSPLStats',
                request_serializer=device__service__pb2.GetSPLStatsRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetSPLStatsResponse.FromString,
                _registered_method=True)
        self.GetSPLByDevice = channel.unary_unary(
                '/device_service.SPLConfigService/GetSPLByDevice',
                request_serializer=device__service__pb2.GetSPLByDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetSPLByDeviceResponse.FromString,
                _registered_method=True)
        self.CalibrateSPL = channel.unary_unary(
                '/device_service.SPLConfigService/CalibrateSPL',
                request_serializer=device__service__pb2.CalibrateSPLRequest.SerializeToString,
                response_deserializer=device__service__pb2.CalibrateSPLResponse.FromString,
                _registered_method=True)
        self.PlayTestTone = channel.unary_unary(
                '/device_service.SPLConfigService/PlayTestTone',
                request_serializer=device__service__pb2.PlayTestToneRequest.SerializeToString,
                response_deserializer=device__service__pb2.PlayTestToneResponse.FromString,
                _registered_method=True)
        self.StopTestTone = channel.unary_unary(
                '/device_service.SPLConfigService/StopTestTone',
                request_serializer=device__service__pb2.StopTestToneRequest.SerializeToString,
                response_deserializer=device__service__pb2.StopTestToneResponse.FromString,
                _registered_method=True)


class SPLConfigServiceServicer:
    """===== SPL 映射 CRUD 服务 =====
    """

    def CreateSPLMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSPLMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSPLMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSPLMappings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSPLMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSPLHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSPLCalibrationData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSPLStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSPLByDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateSPL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayTestTone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTestTone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SPLConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSPLMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSPLMapping,
                    request_deserializer=device__service__pb2.CreateSPLMappingRequest.FromString,
                    response_serializer=device__service__pb2.CreateSPLMappingResponse.SerializeToString,
            ),
            'UpdateSPLMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSPLMapping,
                    request_deserializer=device__service__pb2.UpdateSPLMappingRequest.FromString,
                    response_serializer=device__service__pb2.UpdateSPLMappingResponse.SerializeToString,
            ),
            'DeleteSPLMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSPLMapping,
                    request_deserializer=device__service__pb2.DeleteSPLMappingRequest.FromString,
                    response_serializer=device__service__pb2.DeleteSPLMappingResponse.SerializeToString,
            ),
            'ListSPLMappings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSPLMappings,
                    request_deserializer=device__service__pb2.ListSPLMappingsRequest.FromString,
                    response_serializer=device__service__pb2.ListSPLMappingsResponse.SerializeToString,
            ),
            'GetSPLMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSPLMapping,
                    request_deserializer=device__service__pb2.GetSPLMappingRequest.FromString,
                    response_serializer=device__service__pb2.GetSPLMappingResponse.SerializeToString,
            ),
            'GetSPLHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSPLHistory,
                    request_deserializer=device__service__pb2.GetSPLHistoryRequest.FromString,
                    response_serializer=device__service__pb2.GetSPLHistoryResponse.SerializeToString,
            ),
            'GetSPLCalibrationData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSPLCalibrationData,
                    request_deserializer=device__service__pb2.GetSPLCalibrationDataRequest.FromString,
                    response_serializer=device__service__pb2.GetSPLCalibrationDataResponse.SerializeToString,
            ),
            'GetSPLStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSPLStats,
                    request_deserializer=device__service__pb2.GetSPLStatsRequest.FromString,
                    response_serializer=device__service__pb2.GetSPLStatsResponse.SerializeToString,
            ),
            'GetSPLByDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSPLByDevice,
                    request_deserializer=device__service__pb2.GetSPLByDeviceRequest.FromString,
                    response_serializer=device__service__pb2.GetSPLByDeviceResponse.SerializeToString,
            ),
            'CalibrateSPL': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateSPL,
                    request_deserializer=device__service__pb2.CalibrateSPLRequest.FromString,
                    response_serializer=device__service__pb2.CalibrateSPLResponse.SerializeToString,
            ),
            'PlayTestTone': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTestTone,
                    request_deserializer=device__service__pb2.PlayTestToneRequest.FromString,
                    response_serializer=device__service__pb2.PlayTestToneResponse.SerializeToString,
            ),
            'StopTestTone': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTestTone,
                    request_deserializer=device__service__pb2.StopTestToneRequest.FromString,
                    response_serializer=device__service__pb2.StopTestToneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_service.SPLConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_service.SPLConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SPLConfigService:
    """===== SPL 映射 CRUD 服务 =====
    """

    @staticmethod
    def CreateSPLMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/CreateSPLMapping',
            device__service__pb2.CreateSPLMappingRequest.SerializeToString,
            device__service__pb2.CreateSPLMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSPLMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/UpdateSPLMapping',
            device__service__pb2.UpdateSPLMappingRequest.SerializeToString,
            device__service__pb2.UpdateSPLMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSPLMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/DeleteSPLMapping',
            device__service__pb2.DeleteSPLMappingRequest.SerializeToString,
            device__service__pb2.DeleteSPLMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSPLMappings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/ListSPLMappings',
            device__service__pb2.ListSPLMappingsRequest.SerializeToString,
            device__service__pb2.ListSPLMappingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSPLMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/GetSPLMapping',
            device__service__pb2.GetSPLMappingRequest.SerializeToString,
            device__service__pb2.GetSPLMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSPLHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/GetSPLHistory',
            device__service__pb2.GetSPLHistoryRequest.SerializeToString,
            device__service__pb2.GetSPLHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSPLCalibrationData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/GetSPLCalibrationData',
            device__service__pb2.GetSPLCalibrationDataRequest.SerializeToString,
            device__service__pb2.GetSPLCalibrationDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSPLStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/GetSPLStats',
            device__service__pb2.GetSPLStatsRequest.SerializeToString,
            device__service__pb2.GetSPLStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSPLByDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/GetSPLByDevice',
            device__service__pb2.GetSPLByDeviceRequest.SerializeToString,
            device__service__pb2.GetSPLByDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateSPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/CalibrateSPL',
            device__service__pb2.CalibrateSPLRequest.SerializeToString,
            device__service__pb2.CalibrateSPLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayTestTone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/PlayTestTone',
            device__service__pb2.PlayTestToneRequest.SerializeToString,
            device__service__pb2.PlayTestToneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTestTone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_service.SPLConfigService/StopTestTone',
            device__service__pb2.StopTestToneRequest.SerializeToString,
            device__service__pb2.StopTestToneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
