# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import e2e_service_pb2 as e2e__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in e2e_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub:
    """===== 音频服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayAudio = channel.unary_unary(
                '/e2e_service.AudioService/PlayAudio',
                request_serializer=e2e__service__pb2.PlayAudioRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.PlayAudioResponse.FromString,
                _registered_method=True)
        self.StopAudio = channel.unary_unary(
                '/e2e_service.AudioService/StopAudio',
                request_serializer=e2e__service__pb2.StopAudioRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.StopAudioResponse.FromString,
                _registered_method=True)
        self.GetPlayStatus = channel.unary_unary(
                '/e2e_service.AudioService/GetPlayStatus',
                request_serializer=e2e__service__pb2.GetPlayStatusRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.GetPlayStatusResponse.FromString,
                _registered_method=True)
        self.GetAudioInfo = channel.unary_unary(
                '/e2e_service.AudioService/GetAudioInfo',
                request_serializer=e2e__service__pb2.GetAudioInfoRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.AudioInfoResponse.FromString,
                _registered_method=True)
        self.MeasureSPL = channel.unary_unary(
                '/e2e_service.AudioService/MeasureSPL',
                request_serializer=e2e__service__pb2.MeasureSPLRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.SPLResponse.FromString,
                _registered_method=True)
        self.StartSPL = channel.unary_unary(
                '/e2e_service.AudioService/StartSPL',
                request_serializer=e2e__service__pb2.StartSPLRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.StartSPLResponse.FromString,
                _registered_method=True)
        self.StopSPL = channel.unary_unary(
                '/e2e_service.AudioService/StopSPL',
                request_serializer=e2e__service__pb2.StopSPLRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.StopSPLResponse.FromString,
                _registered_method=True)


class AudioServiceServicer:
    """===== 音频服务 =====
    """

    def PlayAudio(self, request, context):
        """播放音频
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudio(self, request, context):
        """停止播放
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayStatus(self, request, context):
        """获取播放状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudioInfo(self, request, context):
        """获取音频文件信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MeasureSPL(self, request, context):
        """声压级测量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSPL(self, request, context):
        """开始SPL测量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSPL(self, request, context):
        """停止SPL测量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAudio,
                    request_deserializer=e2e__service__pb2.PlayAudioRequest.FromString,
                    response_serializer=e2e__service__pb2.PlayAudioResponse.SerializeToString,
            ),
            'StopAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudio,
                    request_deserializer=e2e__service__pb2.StopAudioRequest.FromString,
                    response_serializer=e2e__service__pb2.StopAudioResponse.SerializeToString,
            ),
            'GetPlayStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayStatus,
                    request_deserializer=e2e__service__pb2.GetPlayStatusRequest.FromString,
                    response_serializer=e2e__service__pb2.GetPlayStatusResponse.SerializeToString,
            ),
            'GetAudioInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudioInfo,
                    request_deserializer=e2e__service__pb2.GetAudioInfoRequest.FromString,
                    response_serializer=e2e__service__pb2.AudioInfoResponse.SerializeToString,
            ),
            'MeasureSPL': grpc.unary_unary_rpc_method_handler(
                    servicer.MeasureSPL,
                    request_deserializer=e2e__service__pb2.MeasureSPLRequest.FromString,
                    response_serializer=e2e__service__pb2.SPLResponse.SerializeToString,
            ),
            'StartSPL': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSPL,
                    request_deserializer=e2e__service__pb2.StartSPLRequest.FromString,
                    response_serializer=e2e__service__pb2.StartSPLResponse.SerializeToString,
            ),
            'StopSPL': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSPL,
                    request_deserializer=e2e__service__pb2.StopSPLRequest.FromString,
                    response_serializer=e2e__service__pb2.StopSPLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2e_service.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e2e_service.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService:
    """===== 音频服务 =====
    """

    @staticmethod
    def PlayAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/PlayAudio',
            e2e__service__pb2.PlayAudioRequest.SerializeToString,
            e2e__service__pb2.PlayAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/StopAudio',
            e2e__service__pb2.StopAudioRequest.SerializeToString,
            e2e__service__pb2.StopAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/GetPlayStatus',
            e2e__service__pb2.GetPlayStatusRequest.SerializeToString,
            e2e__service__pb2.GetPlayStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudioInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/GetAudioInfo',
            e2e__service__pb2.GetAudioInfoRequest.SerializeToString,
            e2e__service__pb2.AudioInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MeasureSPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/MeasureSPL',
            e2e__service__pb2.MeasureSPLRequest.SerializeToString,
            e2e__service__pb2.SPLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/StartSPL',
            e2e__service__pb2.StartSPLRequest.SerializeToString,
            e2e__service__pb2.StartSPLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.AudioService/StopSPL',
            e2e__service__pb2.StopSPLRequest.SerializeToString,
            e2e__service__pb2.StopSPLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceServiceStub:
    """===== 设备驱动服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDriver = channel.unary_unary(
                '/e2e_service.DeviceService/CreateDriver',
                request_serializer=e2e__service__pb2.CreateDriverRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.CreateDriverResponse.FromString,
                _registered_method=True)
        self.DestroyDriver = channel.unary_unary(
                '/e2e_service.DeviceService/DestroyDriver',
                request_serializer=e2e__service__pb2.DestroyDriverRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.DestroyDriverResponse.FromString,
                _registered_method=True)
        self.RegisterTaskEvents = channel.unary_unary(
                '/e2e_service.DeviceService/RegisterTaskEvents',
                request_serializer=e2e__service__pb2.RegisterTaskEventsRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.RegisterTaskEventsResponse.FromString,
                _registered_method=True)
        self.UnregisterTaskEvents = channel.unary_unary(
                '/e2e_service.DeviceService/UnregisterTaskEvents',
                request_serializer=e2e__service__pb2.UnregisterTaskEventsRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.UnregisterTaskEventsResponse.FromString,
                _registered_method=True)
        self.GetTaskEvents = channel.unary_unary(
                '/e2e_service.DeviceService/GetTaskEvents',
                request_serializer=e2e__service__pb2.GetTaskEventsRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.GetTaskEventsResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """===== 设备驱动服务 =====
    """

    def CreateDriver(self, request, context):
        """创建设备驱动（连接设备）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyDriver(self, request, context):
        """销毁设备驱动
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTaskEvents(self, request, context):
        """注册任务事件回调
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterTaskEvents(self, request, context):
        """注销任务事件回调
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskEvents(self, request, context):
        """获取任务事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDriver,
                    request_deserializer=e2e__service__pb2.CreateDriverRequest.FromString,
                    response_serializer=e2e__service__pb2.CreateDriverResponse.SerializeToString,
            ),
            'DestroyDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyDriver,
                    request_deserializer=e2e__service__pb2.DestroyDriverRequest.FromString,
                    response_serializer=e2e__service__pb2.DestroyDriverResponse.SerializeToString,
            ),
            'RegisterTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTaskEvents,
                    request_deserializer=e2e__service__pb2.RegisterTaskEventsRequest.FromString,
                    response_serializer=e2e__service__pb2.RegisterTaskEventsResponse.SerializeToString,
            ),
            'UnregisterTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterTaskEvents,
                    request_deserializer=e2e__service__pb2.UnregisterTaskEventsRequest.FromString,
                    response_serializer=e2e__service__pb2.UnregisterTaskEventsResponse.SerializeToString,
            ),
            'GetTaskEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskEvents,
                    request_deserializer=e2e__service__pb2.GetTaskEventsRequest.FromString,
                    response_serializer=e2e__service__pb2.GetTaskEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2e_service.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e2e_service.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """===== 设备驱动服务 =====
    """

    @staticmethod
    def CreateDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceService/CreateDriver',
            e2e__service__pb2.CreateDriverRequest.SerializeToString,
            e2e__service__pb2.CreateDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceService/DestroyDriver',
            e2e__service__pb2.DestroyDriverRequest.SerializeToString,
            e2e__service__pb2.DestroyDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceService/RegisterTaskEvents',
            e2e__service__pb2.RegisterTaskEventsRequest.SerializeToString,
            e2e__service__pb2.RegisterTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceService/UnregisterTaskEvents',
            e2e__service__pb2.UnregisterTaskEventsRequest.SerializeToString,
            e2e__service__pb2.UnregisterTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceService/GetTaskEvents',
            e2e__service__pb2.GetTaskEventsRequest.SerializeToString,
            e2e__service__pb2.GetTaskEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaybackServiceStub:
    """===== 播放编排服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPlayback = channel.unary_unary(
                '/e2e_service.PlaybackService/StartPlayback',
                request_serializer=e2e__service__pb2.StartPlaybackRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.StartPlaybackResponse.FromString,
                _registered_method=True)
        self.StopPlayback = channel.unary_unary(
                '/e2e_service.PlaybackService/StopPlayback',
                request_serializer=e2e__service__pb2.StopPlaybackRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.StopPlaybackResponse.FromString,
                _registered_method=True)


class PlaybackServiceServicer:
    """===== 播放编排服务 =====
    """

    def StartPlayback(self, request, context):
        """开始播放编排
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPlayback(self, request, context):
        """停止播放编排
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlayback,
                    request_deserializer=e2e__service__pb2.StartPlaybackRequest.FromString,
                    response_serializer=e2e__service__pb2.StartPlaybackResponse.SerializeToString,
            ),
            'StopPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPlayback,
                    request_deserializer=e2e__service__pb2.StopPlaybackRequest.FromString,
                    response_serializer=e2e__service__pb2.StopPlaybackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2e_service.PlaybackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e2e_service.PlaybackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackService:
    """===== 播放编排服务 =====
    """

    @staticmethod
    def StartPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.PlaybackService/StartPlayback',
            e2e__service__pb2.StartPlaybackRequest.SerializeToString,
            e2e__service__pb2.StartPlaybackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.PlaybackService/StopPlayback',
            e2e__service__pb2.StopPlaybackRequest.SerializeToString,
            e2e__service__pb2.StopPlaybackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceResultServiceStub:
    """===== 设备结果采集服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectResult = channel.unary_unary(
                '/e2e_service.DeviceResultService/CollectResult',
                request_serializer=e2e__service__pb2.CollectResultRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.CollectResultResponse.FromString,
                _registered_method=True)
        self.ReextractResult = channel.unary_unary(
                '/e2e_service.DeviceResultService/ReextractResult',
                request_serializer=e2e__service__pb2.ReextractResultRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.ReextractResultResponse.FromString,
                _registered_method=True)


class DeviceResultServiceServicer:
    """===== 设备结果采集服务 =====
    """

    def CollectResult(self, request, context):
        """采集设备结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReextractResult(self, request, context):
        """重新提取设备结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceResultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectResult': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectResult,
                    request_deserializer=e2e__service__pb2.CollectResultRequest.FromString,
                    response_serializer=e2e__service__pb2.CollectResultResponse.SerializeToString,
            ),
            'ReextractResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReextractResult,
                    request_deserializer=e2e__service__pb2.ReextractResultRequest.FromString,
                    response_serializer=e2e__service__pb2.ReextractResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2e_service.DeviceResultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e2e_service.DeviceResultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceResultService:
    """===== 设备结果采集服务 =====
    """

    @staticmethod
    def CollectResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceResultService/CollectResult',
            e2e__service__pb2.CollectResultRequest.SerializeToString,
            e2e__service__pb2.CollectResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReextractResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.DeviceResultService/ReextractResult',
            e2e__service__pb2.ReextractResultRequest.SerializeToString,
            e2e__service__pb2.ReextractResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnvDeviceServiceStub:
    """===== 环境设备服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlEnvDevice = channel.unary_unary(
                '/e2e_service.EnvDeviceService/ControlEnvDevice',
                request_serializer=e2e__service__pb2.ControlEnvDeviceRequest.SerializeToString,
                response_deserializer=e2e__service__pb2.ControlEnvDeviceResponse.FromString,
                _registered_method=True)


class EnvDeviceServiceServicer:
    """===== 环境设备服务 =====
    """

    def ControlEnvDevice(self, request, context):
        """控制环境设备（导轨旋转等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlEnvDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlEnvDevice,
                    request_deserializer=e2e__service__pb2.ControlEnvDeviceRequest.FromString,
                    response_serializer=e2e__service__pb2.ControlEnvDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2e_service.EnvDeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e2e_service.EnvDeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvDeviceService:
    """===== 环境设备服务 =====
    """

    @staticmethod
    def ControlEnvDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e2e_service.EnvDeviceService/ControlEnvDevice',
            e2e__service__pb2.ControlEnvDeviceRequest.SerializeToString,
            e2e__service__pb2.ControlEnvDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
