# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import report_service_pb2 as report__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in report_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportConfigServiceStub:
    """===== 报告配置服务（CRUD + 查询）=====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReport = channel.unary_unary(
                '/report.ReportConfigService/CreateReport',
                request_serializer=report__service__pb2.CreateReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.UpdateReport = channel.unary_unary(
                '/report.ReportConfigService/UpdateReport',
                request_serializer=report__service__pb2.UpdateReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.DeleteReport = channel.unary_unary(
                '/report.ReportConfigService/DeleteReport',
                request_serializer=report__service__pb2.DeleteReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.BatchActionReports = channel.unary_unary(
                '/report.ReportConfigService/BatchActionReports',
                request_serializer=report__service__pb2.BatchActionReportsRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.ListReports = channel.unary_unary(
                '/report.ReportConfigService/ListReports',
                request_serializer=report__service__pb2.ListReportsRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GetReportDetail = channel.unary_unary(
                '/report.ReportConfigService/GetReportDetail',
                request_serializer=report__service__pb2.GetReportDetailRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GetReportByTask = channel.unary_unary(
                '/report.ReportConfigService/GetReportByTask',
                request_serializer=report__service__pb2.GetReportByTaskRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/report.ReportConfigService/GenerateReport',
                request_serializer=report__service__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.UpdateReportStatus = channel.unary_unary(
                '/report.ReportConfigService/UpdateReportStatus',
                request_serializer=report__service__pb2.UpdateReportStatusRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GenerateTaskReport = channel.unary_unary(
                '/report.ReportConfigService/GenerateTaskReport',
                request_serializer=report__service__pb2.GenerateTaskReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GenerateCompareReport = channel.unary_unary(
                '/report.ReportConfigService/GenerateCompareReport',
                request_serializer=report__service__pb2.GenerateCompareReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GenerateSecondaryCompareReport = channel.unary_unary(
                '/report.ReportConfigService/GenerateSecondaryCompareReport',
                request_serializer=report__service__pb2.GenerateSecondaryCompareReportRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GetReportCases = channel.unary_unary(
                '/report.ReportConfigService/GetReportCases',
                request_serializer=report__service__pb2.GetReportCasesRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.SearchReportCases = channel.unary_unary(
                '/report.ReportConfigService/SearchReportCases',
                request_serializer=report__service__pb2.SearchReportCasesRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.ExportReports = channel.unary_unary(
                '/report.ReportConfigService/ExportReports',
                request_serializer=report__service__pb2.ExportReportsRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.GetCaseAverages = channel.unary_unary(
                '/report.ReportConfigService/GetCaseAverages',
                request_serializer=report__service__pb2.GetCaseAveragesRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.DownloadCaseLogs = channel.unary_unary(
                '/report.ReportConfigService/DownloadCaseLogs',
                request_serializer=report__service__pb2.DownloadCaseLogsRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)
        self.BuildReferenceParams = channel.unary_unary(
                '/report.ReportConfigService/BuildReferenceParams',
                request_serializer=report__service__pb2.BuildReferenceParamsRequest.SerializeToString,
                response_deserializer=report__service__pb2.ReportConfigResponse.FromString,
                _registered_method=True)


class ReportConfigServiceServicer:
    """===== 报告配置服务（CRUD + 查询）=====
    """

    def CreateReport(self, request, context):
        """创建报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReport(self, request, context):
        """更新报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReport(self, request, context):
        """删除报告（逻辑删除）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchActionReports(self, request, context):
        """批量操作报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReports(self, request, context):
        """查询报告列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportDetail(self, request, context):
        """查询单个报告详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportByTask(self, request, context):
        """按任务查询报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """生成报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReportStatus(self, request, context):
        """更新报告状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTaskReport(self, request, context):
        """生成任务报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCompareReport(self, request, context):
        """生成对比报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSecondaryCompareReport(self, request, context):
        """生成二次对比报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportCases(self, request, context):
        """查询报告用例列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchReportCases(self, request, context):
        """搜索报告用例
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportReports(self, request, context):
        """导出报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCaseAverages(self, request, context):
        """查询用例平均值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadCaseLogs(self, request, context):
        """下载用例日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildReferenceParams(self, request, context):
        """构建参考参数（供 api_gateway task_query_service 调用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReport,
                    request_deserializer=report__service__pb2.CreateReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'UpdateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReport,
                    request_deserializer=report__service__pb2.UpdateReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'DeleteReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReport,
                    request_deserializer=report__service__pb2.DeleteReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'BatchActionReports': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchActionReports,
                    request_deserializer=report__service__pb2.BatchActionReportsRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'ListReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReports,
                    request_deserializer=report__service__pb2.ListReportsRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GetReportDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportDetail,
                    request_deserializer=report__service__pb2.GetReportDetailRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GetReportByTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportByTask,
                    request_deserializer=report__service__pb2.GetReportByTaskRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=report__service__pb2.GenerateReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'UpdateReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReportStatus,
                    request_deserializer=report__service__pb2.UpdateReportStatusRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GenerateTaskReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTaskReport,
                    request_deserializer=report__service__pb2.GenerateTaskReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GenerateCompareReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompareReport,
                    request_deserializer=report__service__pb2.GenerateCompareReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GenerateSecondaryCompareReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSecondaryCompareReport,
                    request_deserializer=report__service__pb2.GenerateSecondaryCompareReportRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GetReportCases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportCases,
                    request_deserializer=report__service__pb2.GetReportCasesRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'SearchReportCases': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchReportCases,
                    request_deserializer=report__service__pb2.SearchReportCasesRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'ExportReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportReports,
                    request_deserializer=report__service__pb2.ExportReportsRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'GetCaseAverages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCaseAverages,
                    request_deserializer=report__service__pb2.GetCaseAveragesRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'DownloadCaseLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadCaseLogs,
                    request_deserializer=report__service__pb2.DownloadCaseLogsRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
            'BuildReferenceParams': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildReferenceParams,
                    request_deserializer=report__service__pb2.BuildReferenceParamsRequest.FromString,
                    response_serializer=report__service__pb2.ReportConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'report.ReportConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('report.ReportConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportConfigService:
    """===== 报告配置服务（CRUD + 查询）=====
    """

    @staticmethod
    def CreateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/CreateReport',
            report__service__pb2.CreateReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/UpdateReport',
            report__service__pb2.UpdateReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/DeleteReport',
            report__service__pb2.DeleteReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchActionReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/BatchActionReports',
            report__service__pb2.BatchActionReportsRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/ListReports',
            report__service__pb2.ListReportsRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GetReportDetail',
            report__service__pb2.GetReportDetailRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportByTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GetReportByTask',
            report__service__pb2.GetReportByTaskRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GenerateReport',
            report__service__pb2.GenerateReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/UpdateReportStatus',
            report__service__pb2.UpdateReportStatusRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTaskReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GenerateTaskReport',
            report__service__pb2.GenerateTaskReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCompareReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GenerateCompareReport',
            report__service__pb2.GenerateCompareReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSecondaryCompareReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GenerateSecondaryCompareReport',
            report__service__pb2.GenerateSecondaryCompareReportRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GetReportCases',
            report__service__pb2.GetReportCasesRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchReportCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/SearchReportCases',
            report__service__pb2.SearchReportCasesRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/ExportReports',
            report__service__pb2.ExportReportsRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCaseAverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/GetCaseAverages',
            report__service__pb2.GetCaseAveragesRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadCaseLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/DownloadCaseLogs',
            report__service__pb2.DownloadCaseLogsRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildReferenceParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportConfigService/BuildReferenceParams',
            report__service__pb2.BuildReferenceParamsRequest.SerializeToString,
            report__service__pb2.ReportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
