# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import task_service_pb2 as task__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in task_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionServiceStub:
    """===== 执行引擎服务 =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/task_service.ExecutionService/CreateTask',
                request_serializer=task__service__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=task__service__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.StartTask = channel.unary_unary(
                '/task_service.ExecutionService/StartTask',
                request_serializer=task__service__pb2.StartTaskRequest.SerializeToString,
                response_deserializer=task__service__pb2.StartTaskResponse.FromString,
                _registered_method=True)
        self.StopTask = channel.unary_unary(
                '/task_service.ExecutionService/StopTask',
                request_serializer=task__service__pb2.StopTaskRequest.SerializeToString,
                response_deserializer=task__service__pb2.StopTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/task_service.ExecutionService/GetTaskStatus',
                request_serializer=task__service__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=task__service__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.Reevaluate = channel.unary_unary(
                '/task_service.ExecutionService/Reevaluate',
                request_serializer=task__service__pb2.ReevaluateRequest.SerializeToString,
                response_deserializer=task__service__pb2.ReevaluateResponse.FromString,
                _registered_method=True)
        self.GetEngineInfo = channel.unary_unary(
                '/task_service.ExecutionService/GetEngineInfo',
                request_serializer=task__service__pb2.GetEngineInfoRequest.SerializeToString,
                response_deserializer=task__service__pb2.EngineInfoResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer:
    """===== 执行引擎服务 =====
    """

    def CreateTask(self, request, context):
        """创建任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTask(self, request, context):
        """启动任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTask(self, request, context):
        """停止任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """获取任务状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reevaluate(self, request, context):
        """重新评估
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineInfo(self, request, context):
        """获取执行引擎实例信息（如线程池状态）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=task__service__pb2.CreateTaskRequest.FromString,
                    response_serializer=task__service__pb2.CreateTaskResponse.SerializeToString,
            ),
            'StartTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=task__service__pb2.StartTaskRequest.FromString,
                    response_serializer=task__service__pb2.StartTaskResponse.SerializeToString,
            ),
            'StopTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTask,
                    request_deserializer=task__service__pb2.StopTaskRequest.FromString,
                    response_serializer=task__service__pb2.StopTaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=task__service__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=task__service__pb2.TaskStatusResponse.SerializeToString,
            ),
            'Reevaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Reevaluate,
                    request_deserializer=task__service__pb2.ReevaluateRequest.FromString,
                    response_serializer=task__service__pb2.ReevaluateResponse.SerializeToString,
            ),
            'GetEngineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineInfo,
                    request_deserializer=task__service__pb2.GetEngineInfoRequest.FromString,
                    response_serializer=task__service__pb2.EngineInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task_service.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('task_service.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService:
    """===== 执行引擎服务 =====
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/CreateTask',
            task__service__pb2.CreateTaskRequest.SerializeToString,
            task__service__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/StartTask',
            task__service__pb2.StartTaskRequest.SerializeToString,
            task__service__pb2.StartTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/StopTask',
            task__service__pb2.StopTaskRequest.SerializeToString,
            task__service__pb2.StopTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/GetTaskStatus',
            task__service__pb2.GetTaskStatusRequest.SerializeToString,
            task__service__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reevaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/Reevaluate',
            task__service__pb2.ReevaluateRequest.SerializeToString,
            task__service__pb2.ReevaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_service.ExecutionService/GetEngineInfo',
            task__service__pb2.GetEngineInfoRequest.SerializeToString,
            task__service__pb2.EngineInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
