# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transfer_agent_pb2 as transfer__agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transfer_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransferAgentServiceStub:
    """===== 跨区网络传输服务（transfer_agent，T-A / T-B 双实例形态）=====

    职责：跨区传输链路的打包、分片、签名、续传、校验（设计文档 09_跨区网络传输方案 §4.2）。
    调用方：
    - 本区微服务（evaluation_service / task_service / report_service）经 gRPC 发起传输
    - 远端 transfer_agent 经 HTTP /internal/transfer/* 收包（跨区走 HTTPS 过网关）

    传输包协议字段（transfer_id / pkg_type / signature / ttl / ephemeral 等）见
    CreateTransferRequest；签名规则：hmac_sha256(预共享token, canonical_string)，
    canonical_string 见 transfer_agent.domain.services.signature_service。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTransfer = channel.unary_unary(
                '/transfer.TransferAgentService/CreateTransfer',
                request_serializer=transfer__agent__pb2.CreateTransferRequest.SerializeToString,
                response_deserializer=transfer__agent__pb2.TransferActionResponse.FromString,
                _registered_method=True)
        self.UploadChunk = channel.unary_unary(
                '/transfer.TransferAgentService/UploadChunk',
                request_serializer=transfer__agent__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=transfer__agent__pb2.TransferActionResponse.FromString,
                _registered_method=True)
        self.GetTransferStatus = channel.unary_unary(
                '/transfer.TransferAgentService/GetTransferStatus',
                request_serializer=transfer__agent__pb2.GetTransferStatusRequest.SerializeToString,
                response_deserializer=transfer__agent__pb2.TransferStatusResponse.FromString,
                _registered_method=True)
        self.CompleteTransfer = channel.unary_unary(
                '/transfer.TransferAgentService/CompleteTransfer',
                request_serializer=transfer__agent__pb2.CompleteTransferRequest.SerializeToString,
                response_deserializer=transfer__agent__pb2.TransferActionResponse.FromString,
                _registered_method=True)
        self.GetTransfer = channel.unary_unary(
                '/transfer.TransferAgentService/GetTransfer',
                request_serializer=transfer__agent__pb2.GetTransferRequest.SerializeToString,
                response_deserializer=transfer__agent__pb2.TransferStatusResponse.FromString,
                _registered_method=True)


class TransferAgentServiceServicer:
    """===== 跨区网络传输服务（transfer_agent，T-A / T-B 双实例形态）=====

    职责：跨区传输链路的打包、分片、签名、续传、校验（设计文档 09_跨区网络传输方案 §4.2）。
    调用方：
    - 本区微服务（evaluation_service / task_service / report_service）经 gRPC 发起传输
    - 远端 transfer_agent 经 HTTP /internal/transfer/* 收包（跨区走 HTTPS 过网关）

    传输包协议字段（transfer_id / pkg_type / signature / ttl / ephemeral 等）见
    CreateTransferRequest；签名规则：hmac_sha256(预共享token, canonical_string)，
    canonical_string 见 transfer_agent.domain.services.signature_service。
    """

    def CreateTransfer(self, request, context):
        """创建传输会话（幂等：同 transfer_id 且 file_hash 一致直接返回已存在会话）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadChunk(self, request, context):
        """上传一个分片（幂等去重：同分片同 checksum 重复上传直接成功）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransferStatus(self, request, context):
        """查询传输状态与已收分片清单（断点续传依据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTransfer(self, request, context):
        """结束传输：合并分片 + file_hash 完整性校验
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransfer(self, request, context):
        """查询传输包元数据（含审计流水字段）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTransfer,
                    request_deserializer=transfer__agent__pb2.CreateTransferRequest.FromString,
                    response_serializer=transfer__agent__pb2.TransferActionResponse.SerializeToString,
            ),
            'UploadChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadChunk,
                    request_deserializer=transfer__agent__pb2.UploadChunkRequest.FromString,
                    response_serializer=transfer__agent__pb2.TransferActionResponse.SerializeToString,
            ),
            'GetTransferStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransferStatus,
                    request_deserializer=transfer__agent__pb2.GetTransferStatusRequest.FromString,
                    response_serializer=transfer__agent__pb2.TransferStatusResponse.SerializeToString,
            ),
            'CompleteTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTransfer,
                    request_deserializer=transfer__agent__pb2.CompleteTransferRequest.FromString,
                    response_serializer=transfer__agent__pb2.TransferActionResponse.SerializeToString,
            ),
            'GetTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransfer,
                    request_deserializer=transfer__agent__pb2.GetTransferRequest.FromString,
                    response_serializer=transfer__agent__pb2.TransferStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transfer.TransferAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transfer.TransferAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransferAgentService:
    """===== 跨区网络传输服务（transfer_agent，T-A / T-B 双实例形态）=====

    职责：跨区传输链路的打包、分片、签名、续传、校验（设计文档 09_跨区网络传输方案 §4.2）。
    调用方：
    - 本区微服务（evaluation_service / task_service / report_service）经 gRPC 发起传输
    - 远端 transfer_agent 经 HTTP /internal/transfer/* 收包（跨区走 HTTPS 过网关）

    传输包协议字段（transfer_id / pkg_type / signature / ttl / ephemeral 等）见
    CreateTransferRequest；签名规则：hmac_sha256(预共享token, canonical_string)，
    canonical_string 见 transfer_agent.domain.services.signature_service。
    """

    @staticmethod
    def CreateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transfer.TransferAgentService/CreateTransfer',
            transfer__agent__pb2.CreateTransferRequest.SerializeToString,
            transfer__agent__pb2.TransferActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transfer.TransferAgentService/UploadChunk',
            transfer__agent__pb2.UploadChunkRequest.SerializeToString,
            transfer__agent__pb2.TransferActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransferStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transfer.TransferAgentService/GetTransferStatus',
            transfer__agent__pb2.GetTransferStatusRequest.SerializeToString,
            transfer__agent__pb2.TransferStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transfer.TransferAgentService/CompleteTransfer',
            transfer__agent__pb2.CompleteTransferRequest.SerializeToString,
            transfer__agent__pb2.TransferActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transfer.TransferAgentService/GetTransfer',
            transfer__agent__pb2.GetTransferRequest.SerializeToString,
            transfer__agent__pb2.TransferStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
