# This file created by conda-build 26.3.0
# meta.yaml template originally from:
# C:\Users\task_IzTv_XtETmOVg_0\ca-certificates-feedstock\recipe, last modified Mon Jul 20 08:45:19 2026
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2026.7.16
source:
  fn: cacert.pem
  url: https://curl.se/ca/cacert-2026-07-16.pem
  sha256: 3ff344e30b9b1ed2971044eabb438a08f2e2245ddb5f8ab1a3ad8b63ab4eaf91
build:
  number: '0'
  string: haa95532_0
requirements:
  build: []
  run: []
test:
  requires:
    - curl
about:
  home: https://curl.se/docs/caextract.html
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: Certificates for use with other packages.
  description: Certificates for use with other packages.
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  dev_url: https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
  skip-lints:
    - missing_section
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/ca-certificates-feedstock
  sha: 9674b04ac6ef838169662800567da635f9107b5a
  task_id: IzTv_XtETmOVg17Ta8hoVg
  task_run_id: '0'
  pbp_graph_uuid: 776c6cb4-128b-450c-a77b-1d4a8f89df3f
