# This file created by conda-build 26.3.0
# ------------------------------------------------

package:
  name: vc
  version: 14.3
source:
  - url: https://download.visualstudio.microsoft.com/download/pr/c7dac50a-e3e8-40f6-bbb2-9cc4e3dfcabe/1821577409C35B2B9505AC833E246376CC68A8262972100444010B57226F0940/vc_redist.x64.exe
    sha256: 1821577409c35b2b9505ac833e246376cc68a8262972100444010b57226f0940
build:
  number: 12
  string: h2df5915_12
requirements:
  run:
    - vc14_runtime >=14.42.34433
  build: []
test:
  commands: echo "this is an empty wrapper package"
about:
  home: https://github.com/conda/conda/wiki/VC-features
  license: BSD-3-Clause
  license_family: BSD
  summary: A meta-package to impose mutual exclusivity among software built with different
    VS versions
  description: This metapackage is used to enforce consistency of runtime dependencies
    within an environment
  doc_url: https://github.com/conda/conda/wiki/VC-features
  dev_url: https://github.com/conda/conda/wiki/VC-features
extra:
  feedstock-name: vc
  recipe-maintainers:
    - 183amir
    - isuruf
    - jakirkham
    - msarahan
    - patricksnape
    - pelson
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/vc-feedstock
  sha: b485060ed57d44bcf3fe7da8578336f6b151a94c
  task_id: PjrSVvhZSnqKsxLHyRPF8A
  task_run_id: '0'
  pbp_graph_uuid: e62a1289-3d65-44ab-8e6a-6a79f478e3d5
